### ISSUE TITLE
Future of EOA/AA Breakout Room #2

### ISSUE THREAD

**Issue by lightclient** [ethereum/pm#1032]
# Meeting Info
* [May 7 2024, 14:00-15:30 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20240507T140000&p1=1440&p2=37&p3=136&p4=237&p5=923&p6=204&p7=671&p8=16&p9=41&p10=107&p11=28)
* Zoom: see the #allcoredevs channel of the R&D discord
* [Ethereum Protocol Calls Calendar subscription](https://calendar.google.com/calendar/u/0?cid=Y191cGFvZm9uZzhtZ3JtcmtlZ243aWM3aGs1c0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t)

Agenda
* In-protocol AA roadmap
    * Account migration
    * Smart account originated transactions
    * Relationship with EIP-3074
    * QC mitigations, long term EOA management
* EIP-3074
    * Alternatives
        * [Proposal from Vitalik: EIP-7702](https://github.com/ethereum/EIPs/blob/vbuterin-patch-1/EIPS/eip-7702.md)
        * [Combining 5806 with 3074](https://gist.github.com/lightclient/0d8d91264e7875cec4341de930d347ad)
    * Reusing existing infrastructure
        * 3074 in 4337            
    * Adding flexibility for chain id / nonce in auth msg
        * Remove completely
        * Opt-out with value `0`
    * Propagate `authorized` with `DELEGATECALL`

**Comment by ankurdubey521** [comment]
Does "Account Migration" include discussions on EIP5003?

**Comment by lightclient** [comment]
@ankurdubey521 yes it does.

**Comment by Fishbiscuit** [comment]
As mentioned in the AA Mafia group, I’m making a request to adjust the agenda to facilitate for more community feedback.

Agenda

1. EIP-3074 clarifications
  - Technical specifications
  - Enabling other AA-related EIPs
  - Changes to EOAs and further impact

2. Proposed EIP-3074 changes
  - Summary of changes being proposed and rationale
  - Reusing existing infrastructure
     - 3074 in 4337
     - Smart account code as invokers
     - [Combining 5806 with 3074](https://gist.github.com/lightclient/0d8d91264e7875cec4341de930d347ad)
  - Adding flexibility for chain id / nonce in auth msg
     - Remove completely
     - Opt-out with value `0`
  - Propagate `authorized` with `DELEGATECALL`

3. In-protocol AA roadmap

4. Any other business

**Comment by rmeissner** [comment]
Late addition:
Alternative to 3074: https://hackmd.io/@vbuterin/3074_via_tx_type
  - Useful reference is [EIP-5806](https://eips.ethereum.org/EIPS/eip-5806)

**Comment by poojaranjan** [comment]
Recording: https://youtu.be/GPdbQxmsXR8
