### ISSUE TITLE
ePBS breakout room #2

### ISSUE THREAD

**Issue by potuz** [ethereum/pm#1060]
* [June 7 (Fri), 2024 , **14:00 UTC**](https://www.timeanddate.com/worldclock/converter.html?iso=20240607T140000&p1=tz_gmt&p2=1440) :clock2: ❗
* Duration: 60 minutes
* [Zoom link](https://ethereumfoundation.zoom.us/j/87569210985?pwd=3Cv1hDh7If4cq9IMXvNln1CtqQ72MR.1)

## Agenda
* EIP Status
* Spec discussion
* Implementation complexity discussion

**Comment by terencechain** [comment]
If time permits, I'd love to chat about the current status of (block, slot) fork choice analysis for ePBS. As analysis done in these documents:
- https://ethresear.ch/t/sandwitch-attacks-on-epbs/19538
- https://hackmd.io/@potuz/rJ9GCnT1C#Forkchoice-considerations

Besides the current post-anti and ex-anti analysis of two slots sandwich attacks, what other analysis/attack is worth studying over. One example is multi-slot liveness attack. As the performance of network conditions becomes worse, chain growth stops completely if block latency is > 3 seconds. Whether a backoff scheme is necessary to facilitate chain progression during periods of extended latency

**Comment by hwwhww** [comment]
@potuz 
you should not use 🕙 emoji here 😄

**Comment by potuz** [comment]
Lol copied from a different issue :)

**Comment by potuz** [comment]
If there's time (writing here mostly for the next breakout) I'd like to brainstorm how an "off-protocol" solution actually would play out. It seems to me that ePBS makes any out of protocol solution very very hard to be viable.

**Comment by terencechain** [comment]
> If there's time (writing here mostly for the next breakout) I'd like to brainstorm how an "off-protocol" solution actually would play out. It seems to me that ePBS makes any out of protocol solution very very hard to be viable.

I wrote a post today on out-of-protocol timelines under ePBS: https://hackmd.io/@ttsao/comp_epbs_timelines. It's the worst of both worlds.

**Comment by terencechain** [comment]
Call notes https://hackmd.io/@ttsao/epbs-breakout2

**Comment by shyam-patel-kira** [comment]
Was the session recorded?

**Comment by poojaranjan** [comment]
Recording: https://youtu.be/w7Wa6oprEhQ

Please refer [ePBS Playlist](https://www.youtube.com/playlist?list=PLJqWcTqh_zKHoz9dnQFGrWI_s1-8RwMhX) for other meetings.

**Comment by shyam-patel-kira** [comment]
Thanks @poojaranjan!
