### ISSUE TITLE
ePBS Breakout room #3

### ISSUE THREAD

**Issue by potuz** [ethereum/pm#1067]
* [June 21 (Fri), 2024 , **14:00 UTC**](https://www.timeanddate.com/worldclock/converter.html?iso=20240621T140000&p1=tz_gmt&p2=1440) :clock2: ❗
* Duration: 60 minutes
* [Zoom link](https://ethereumfoundation.zoom.us/j/87569210985?pwd=3Cv1hDh7If4cq9IMXvNln1CtqQ72MR.1)

## Agenda
* EIP Status
* Advantages/Disadvantages for builders/proposers to not use the in-protocol auction.

**Comment by terencechain** [comment]
If time permits, I want to discuss the Beacon API complications related to the get_block function. Currently, get_block returns the full block, which includes both consensus and execution parts. However, most CL clients do not store the execution part and rely on an EL client to blind/unblind it upon request. With ePBS, the consensus-only block becomes the first class citizen on the CL side. It would make sense for the Beacon API specification to assume get_block always returns the first-class consensus block. If users need the execution block, they should retrieve it from the execution API endpoint. This would significantly reduce design complexity by avoiding the need for a third block type that would be used only for the Beacon API.

**Comment by terencechain** [comment]
Call notes: https://hackmd.io/@ttsao/epbs-breakout3

**Comment by poojaranjan** [comment]
Recording: https://youtu.be/J1e5iUvcTDU
