### ISSUE TITLE
ePBS Breakout room #4

### ISSUE THREAD

**Issue by potuz** [ethereum/pm#1083]
* [July 5th (Fri), 2024 , **14:00 UTC**](https://www.timeanddate.com/worldclock/converter.html?iso=20240705T140000&p1=tz_gmt&p2=1440) :clock2: ❗
* Duration: 60 minutes
* [Zoom link](https://ethereumfoundation.zoom.us/j/87569210985?pwd=3Cv1hDh7If4cq9IMXvNln1CtqQ72MR.1)
* [Recordings](https://www.youtube.com/playlist?list=PLJqWcTqh_zKHoz9dnQFGrWI_s1-8RwMhX)

## Agenda
* EIP Status
* Advantages/Disadvantages for builders/proposers to not use the in-protocol auction. 
* Process withdrawals with the execution payload
* PTC equivocations
* Gas limit (chosen by proposers instead of builders)
* `get_attesting_indices` invalidates the transaction signature if there are ptc members.

**Comment by potuz** [comment]
I would like to discuss the possibility of moving withdrawal processing to the execution payload entirely instead of a lock-fulfil mechanism where the withdrawal is deducted from the beacon chain when processing the CL block and then later is fulfilled in the EL when processing the execution payload.

**Comment by potuz** [comment]
Another issue to add to the agenda: with the current PTC threshold to achieve consensus at 50%, a malicious builder that wants to create a split view requires a single PTC member to equivocate in order to do so, perhaps raising the threshold to 66% is worth it to avoid this attack.

**Comment by potuz** [comment]
Yet another one if there's time: the current `get_attesting_indices` is a hack. Perhaps we want a cleaner way of dealing with attestations.

**Comment by terencechain** [comment]
Regarding the gas limit, I wonder if the current P2P specification needs modification. Assume the following setup: `validator_a` wants a gas limit of 30M, while `validator_b` wants a gas limit of 40M. The builder knows this disparity and broadcasts two individual bids, one for 40M and one for 30M. The bids need to hop through `validator_a` to get to `validator_b`.

If `validator_a` receives the 30M bid first, it will pass the 30M bid to `validator_b` and drop the 40M bid. Depending on who is proposing, either `a` or `b` will use the 30M bid, even though the `b` prefers the 40M bid.

If `validator_a` receives the 40M bid first, it will pass the 40M bid to `validator_b` and drop the 30M bid. Depending on who is proposing, `a` cannot propose with the 40M bid while `b` can.

**Comment by terencechain** [comment]
In the future, we might want to refer this as EIP-7732 break out

**Comment by poojaranjan** [comment]
Recording: https://youtu.be/WC9XsungamU

**Comment by terencechain** [comment]
Notes: https://hackmd.io/@ttsao/epbs-breakout3
