### ISSUE TITLE
Future of EOA/AA Breakout Room #6

### ISSUE THREAD

**Issue by lightclient** [ethereum/pm#1118]
# Meeting Info
* [July 31 2024, 14:00-15:30 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20240731T140000&p1=1440&p2=37&p3=136&p4=237&p5=923&p6=204&p7=671&p8=16&p9=41&p10=107&p11=28)
* Zoom: see the #allcoredevs channel of the R&D discord
* [Ethereum Protocol Calls Calendar subscription](https://calendar.google.com/calendar/u/0?cid=Y191cGFvZm9uZzhtZ3JtcmtlZ243aWM3aGs1c0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t)

Agenda
* DoS resistance 
* Shared storage issues and [solution](https://github.com/ethereum/EIPs/pull/8762)
* [`CODERESET`](https://hackmd.io/@S9AwbucvTS6GYodLz-G1SQ/S102UtTwA)
* [Add `ORIGIN` to auth tuple](https://github.com/ethereum/EIPs/pull/8763)

**Comment by g11tech** [comment]
https://github.com/ethereum/EIPs/pull/8762 for discussion

**Comment by Jrachman** [comment]
Feel free to use this as a base for the main open threads to discuss: https://hackmd.io/@otim/BkUQJ5RdA

**Comment by ankitchiplunkar** [comment]
https://hackmd.io/@S9AwbucvTS6GYodLz-G1SQ/S102UtTwA

**Comment by poojaranjan** [comment]
Quick note : https://hackmd.io/@poojaranjan/EOA-AA-Breakout#-Future-of-EOAAA-Breakout-Room-6

**Comment by poojaranjan** [comment]
Recording: https://www.youtube.com/watch?v=Oct83bBp3Z8
