### ISSUE TITLE
RollCall #8.1 Breakout - EVM Equivalence on L2: Past, Present, Future

### ISSUE THREAD

**Issue by CarlBeek** [ethereum/pm#1171]
## Meeting Info
- [Wed October 23, 2024, 14:00-15:00 UTC](https://savvytime.com/converter/utc-to-germany-berlin-united-kingdom-london-ny-new-york-city-ca-san-francisco-china-shanghai-japan-tokyo-australia-sydney/oct-23-2024/2pm)
- Zoom link shared on `RIP coordination` in the RollCall channel in the [EthR&D Discord](https://discord.com/invite/qGpsxSA) which is bridged to the RollCall telegram channel shortly before the call.
- Recording: https://www.youtube.com/watch?v=fDIiO63QJog
- Slides:    https://docs.google.com/presentation/d/12t-7bG7bgOh02wQlmrcJrwkEuV5HI_CJux7bIepertE/edit#slide=id.g2e5d90eb79b_0_39

## Agenda
- presentation: EVM Equivalence on L2: Past, Present, Future
    - history
    - current situation
    - our vision
    - next steps
- introduction by the rollup-geth team
- open discussion

**Comment by abcoathup** [comment]
* Recording: https://www.youtube.com/watch?v=fDIiO63QJog
* Slides: https://docs.google.com/presentation/d/12t-7bG7bgOh02wQlmrcJrwkEuV5HI_CJux7bIepertE/edit#slide=id.g2e5d90eb79b_0_39
* Rollup-geth: https://ethereum-magicians.org/t/introducing-rollup-geth/21458
