### ISSUE TITLE
Execution Layer Meeting "💯 💯" 

### ISSUE THREAD

**Issue by timbeiko** [ethereum/pm#1190]
## Meeting Info
* [Nov 7, 2024, 14:00-15:30 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20241107T140000&p1=1440&p2=37&p3=136&p4=237&p5=923&p6=204&p7=671&p8=16&p9=41&p10=107&p11=28)
    * 🕐 **DST notice: double check your local time** 🕐 
    * Scheduling note: the Nov 21 ACDE will be replaced by a client testing call, ACDE 201 will happen on Dec 5 📆 
* Stream: https://youtube.com/live/DqdmqDtm2wM
* Zoom: shared on `#allcoredevs` Discord channel shortly before the call 
* [Ethereum Protocol Calls Calendar subscription](https://calendar.google.com/calendar/u/0?cid=Y191cGFvZm9uZzhtZ3JtcmtlZ243aWM3aGs1c0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t)

## Agenda
* Pectra updates
    * [devnet-4](https://notes.ethereum.org/@ethpandaops/pectra-devnet-4)
    * https://github.com/ethereum/EIPs/pull/9024
    * [EIP-7702 updates](https://github.com/ethereum/EIPs/pull/8969)
    * [Mekong 🏞️](https://blog.ethereum.org/2024/11/07/introducing-mekong-testnet)
    * [devnet-5](https://notes.ethereum.org/@ethpandaops/pectra-devnet-5)
* Individual EIP activations ([context](https://github.com/ethereum/pm/issues/1190#issuecomment-2450838954))
* [eth/70 - Sharded Blocks Protocol](https://github.com/ethereum/EIPs/pull/9004) 
* [EIP-7610 update](https://eips.ethereum.org/EIPS/eip-7610) 
* Devcon & ACD
    * Cancel Nov 14 ACDC
    * [Devcon Ethereum Magicians Session on Nov 15](https://ethereum-magicians.org/t/ethereum-magicians-infinite-endgames-session-devcon-sea/21451)
    * Nov 21 ACDE → Pectra Interop Testing Call

**Comment by smartprogrammer93** [comment]
I would like to propose and discuss https://github.com/ethereum/EIPs/pull/9004

**Comment by ralexstokes** [comment]
This came up on ACDC#145; to help with Fusaka testing it would be nice if CLs and ELs had the flexibility to unset some features, even if there is a hard fork encoded.

The motivating example: Want to run a `fusaka` devnet but only with PeerDAS, and e.g. not also deploy EOF.

What's the best way to address this?

**Comment by fjl** [comment]
Again very late request, but would like to discuss this change to the EIP-7002 contract: https://github.com/ethereum/EIPs/pull/9024

**Comment by akashkshirsagar31** [comment]
Podcast (audio only) ACDE 200🎉 - https://open.spotify.com/episode/2qSX1Pb8HXcmDetaoooqzB?si=rRmsIA5rR-qLlZRL2InejA

**Comment by timbeiko** [comment]
Closed in favor of https://github.com/ethereum/pm/issues/1197
