### ISSUE TITLE
All Core Devs Meeting #14

### ISSUE THREAD

**Issue by Souptacular** [ethereum/pm#12]
# All Core Devs Meeting 14 Agenda
### Meeting Duration 1.5 hours
# Agenda

1. [EIP 186: Reduce ETH issuance before proof-of-stake](https://github.com/ethereum/EIPs/issues/186).
[Carbonvote link](http://www.carbonvote.com/?p1=1).
[Reddit thread #1](https://www.reddit.com/r/ethereum/comments/5lb684/eip186_to_decrease_eth_issuance_by_3x/).
[Reddit thread #2](https://www.reddit.com/r/ethereum/comments/60c2my/carbonvote_set_up_for_eip186/).
2. About EIP86 (a.k.a EIP-208), there is a difference between the EIP pull-request and the implementations. Which should be fixed?
3. Metropolis updates - specifically an update on where each client is at in implementation and an update on the tests. Some accepted EIPs are not yet specific enough to form a protocol consensus. What is the next action by whom?

Please provide comments to add or correct agenda topics.

**Comment by vbuterin** [comment]
Regarding 2, maybe expand to focus on (i) how much every client has implemented, and (ii) how much there are tests for?

**Comment by pirapira** [comment]
3. About [EIP86 a.k.a eip-208](https://github.com/ethereum/EIPs/pull/208), there is a difference between the EIP pull-request and the implementations.  Which should be fixed?

The point is whether to change the addressing scheme of CREATE **instruction**, in addition to the create **transactions**.
* [EIP86 PR](https://github.com/ethereum/EIPs/pull/208#pullrequestreview-32389576) does not change the addressing scheme of CREATE instruction (only the addressing scheme of create transactions change).
* [cpp-ethereum](https://github.com/ethereum/cpp-ethereum/pull/4046/files#diff-595e804f478de48cde3dfe17219495adR186) is going to change the addressing scheme of CREATE instruction.
* [Parity](https://github.com/paritytech/parity/pull/4697/files#diff-2ebfb83ff65a568bc9bbec5c087fd7afR276) is [also](https://github.com/paritytech/parity/pull/4697/files#diff-ef2687136b4e032043a492e9e53dcb7cR164) going to change CREATE instruction.
* [YP PR](https://github.com/ethereum/yellowpaper/pull/277/files#diff-9f702e1491c55da9d76a68d651278764R1958) is also changing CREATE instruction.

**Comment by pirapira** [comment]
2 (iii) some accepted EIPs are not yet specific enough to form a consensus

* [pairing check](https://github.com/ethereum/EIPs/pull/212) has gas costs unspecified.  It also uses an  already-taken address.
* [group addition on elliptic curve](https://github.com/ethereum/EIPs/pull/213/files#diff-7ae37733c4d066156fc1c328464b8996R67) has gas costs unspecified.  It also used an already-taken address.
* https://github.com/ethereum/EIPs/issues/96 has [getter_code] unspecified.

**Comment by gumb0** [comment]
- [removing medstate from receipts](https://github.com/ethereum/EIPs/pull/98) - go & cpp implemented option 2, Parity seems to have went with option 1

**Comment by Souptacular** [comment]
Notes and video added. Closing issues.

https://github.com/ethereum/pm/blob/master/All%20Core%20Devs%20Meetings/Meeting%2014.md
