### ISSUE TITLE
RollCall #8.2 Breakout - L2 EVM Common Core: Kickoff

### ISSUE THREAD

**Issue by adietrichs** [ethereum/pm#1201]
As announced on https://github.com/ethereum/pm/issues/1171, we will have a RollCall breakout call to kick off the L2 EVM Common Core project.

## Meeting Info
* [Wed December 04, 2024, 14:00-15:00 UTC](https://savvytime.com/converter/utc-to-germany-berlin-united-kingdom-london-ny-new-york-city-ca-san-francisco-china-shanghai-japan-tokyo-australia-sydney/dec-04-2024/2pm)
* Zoom link shared on `RIP coordination` in the RollCall channel in the [EthR&D Discord](https://discord.com/invite/qGpsxSA) which is bridged to the RollCall telegram channel shortly before the call.

## Agenda
- meta: L2 EVM common core
  - useful approach?
  - scope / objectives
- first version
  - EVM basis: Dencun or Pectra (or Fusaka)?
  - candidate features

**Comment by axic** [comment]
Please base it on Fusaka 😉

**Comment by abcoathup** [comment]
@adietrichs can you share the recording, any slides and a summary of the breakout including any decisions/actions?

https://ethereum-magicians.org/t/rollcall-8-2-breakout-l2-evm-common-core-kickoff-december-4-2024/21964

**Comment by CarlBeek** [comment]
Recording availible here: https://youtu.be/Rn6vrAEZCP8
