### ISSUE TITLE
FOCIL Break-Out Room

### ISSUE THREAD

**Issue by matthewkeil** [ethereum/pm#1210]
- Friday, December 13th, 2024 @ 2pm UTC
- Duration: 60min meeting

### Agenda
First call to begin discussion of implementation

**Comment by matthewkeil** [comment]
@poojaranjan I was talking with @timbeiko and he mentioned you could help with added a Zoom link and recording this.  Its my first time interacting with this repo so thanks in advance and for the help!!

**Comment by poojaranjan** [comment]
Zoom link : https://us02web.zoom.us/j/89711946955?pwd=1LaWbbQbkVgAW7E6IeW1YwskuivUSp.1

**Comment by matthewkeil** [comment]
# FOCIL Breakout Meeting #1

Date: December 13, 2024 @ 2pm UTC
Zoom: <https://www.google.com/url?q=https://us02web.zoom.us/j/89711946955?pwd%3D1LaWbbQbkVgAW7E6IeW1YwskuivUSp.1&sa=D&source=calendar&ust=1734258054253936&usg=AOvVaw1KxemSj8rzZIdjf1e6paiz>

## Spec Stability

- CL spec is relatively stable
- EL spec will be formalized with a PR to EELS

## Spec Questions

- Fork-Choice slot/block enforcement via proposer-boost reorging.  This might/should need to be a separate EIP

## Inclusions/Exclusions for First Round

- Blobs will not be included
- Maybe not verify IL's for first round of integration testing

## Rough Timeline

- Shoot for first week of January for next meeting
- Hope that by that meeting we can have at least 1 CL and 1 EL ready to test with
- Shoot for attempting to set up a basic Kurtosis/Hive network between the first clients on the next call

## Spec Test Goals

- Engage with Testing group to figure out timeline for work on spec tests

## Active Branches

- Geth: <https://github.com/jihoonsong/go-ethereum/tree/focil>
- Lodestar: <https://github.com/ChainSafe/lodestar/tree/focil>

## References Posted During Call

- <https://meetfocil.eth.limo/>
- <https://notes.ethereum.org/@jacobkaufmann/Sy7sNHKVye>
- <https://hackmd.io/@jihoonsong/BJUVIsY4ye>

## Implementation Notes

Goal should be to keep discussion strictly in Discord and on the website <https://meetfocil.eth.limo>.  Telegram and Twitter should be avoided to help corral the discussion to a single (or two) places.

There are two cases in the execution case. When sync'd and before sync.  Should the CL be notifying the EL to check the IL's?  This will be different cases for when syncing and after sync is complete.  A PR will be opened to the spec to dial this in.

EL will look at specifying that if an IL is passed in then the IL should be checked, if not then the IL's will not need to be verified to check the block.  Terrence requested for @Jihoon to open a pr here? <https://github.com/ethereum/execution-apis/pulls>

**Comment by poojaranjan** [comment]
- FOCIL Playlist - https://www.youtube.com/watch?v=SOt-rNDlsRU&list=PLJqWcTqh_zKFIaCmjgKO4HJLn4y-Rg3He
- Recording: https://youtu.be/SOt-rNDlsRU
