### ISSUE TITLE
Stateless Ethereum Call #5 - Eth1.X

### ISSUE THREAD

**Issue by MadeofTin** [ethereum/pm#157]
Meeting Date/Time: March 24th, 2020 16:00 pm UTC
Meeting Duration 1.5 hours

Agenda

**Comment by pipermerriam** [comment]
Proposed Agenda:

- recap of summit
  - state network no longer on critical path.
  - [the rough roadmap](https://cdn.discordapp.com/attachments/688075293562503241/689527149555875876/file_3.jpg)
- updates
  - witness spec
  - sync
  - gas accounting for witnesses
  - binary tree
- discussions
  - sync
  - rolling out witnesses asap
