### ISSUE TITLE
Sync Working Group - Call #0

### ISSUE THREAD

**Issue by MadeofTin** [ethereum/pm#158]
Polling interest on a Sync working group.

This would be a call primarily focused on client devs to work together towards a common agreed-upon plan to deprecate GetNodeData.

Let me know below if you are interested in participating.

Update:
Scheduled! for 

Time: Tuesday, April 21st at 14:00 UTC.
Agenda:
1. make sure everyone understands the concept/goals that we need to achieve under the new sync algo
2. evaluation of current sync approaches and how they measure up
3. brief high-level evaluation of ideas thus far.

**Comment by MadeofTin** [comment]
Rocket emoji to signal interest. 🚀  

Any questions let me know!

**Comment by pipermerriam** [comment]
Will discuss the percieved efficacy of having this call in #157

**Comment by MadeofTin** [comment]
Scheduled for Tuesday, updated the info above accordingly
