### ISSUE TITLE
EIP Sync call:  Simple Subroutines for the EVM

### ISSUE THREAD

**Issue by MadeofTin** [ethereum/pm#173]
Date: May 18th 2020 13:00 pm UTC
Duration: tbd
Zoom link: tbd.

Agenda:
Discuss final spec for EIP 2315: Simple Subroutines for the EVM.

**Comment by gcolvin** [comment]
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-2315.md

**Comment by chriseth** [comment]
My personal goal for this meeting is to discuss if and how we can properly add the restrictions laid out in https://ethereum-magicians.org/t/eip-2315-simple-subroutines-for-the-evm-analysis/4229 in a way that makes all involved parties happy.

**Comment by MadeofTin** [comment]
Close as the meeting occurred.
