### ISSUE TITLE
EIP 2046 + 2666

### ISSUE THREAD

**Issue by MadeofTin** [ethereum/pm#178]
A call to discuss precompile repricing. Including 
 - [EIP 2046](https://eips.ethereum.org/EIPS/eip-2046)
 - [EIP 2666](https://github.com/ethereum/EIPs/pull/2666)

Schedule: Friday
Zoom Link: TBD

Agenda:
- Finalize number for 2046
- Decide if 2666 should be split into precompiles and EVM part
- Check if Go implementation of Keccak256 can be improved to match the speed of Rust (huge difference in performance in my tests)

Please let me know here or through DM if you would like to be added to the Calendar Event. Thank you!

**Comment by axic** [comment]
Thursday is probably the worst possible time for this. Would suggest Friday instead. I'd hope @holiman can participate.

**Comment by shamatar** [comment]
Both Tuesday or Friday are ok for me. 

Shortly on agenda:
- Finalize number for 2046
- Decide if 2666 should be split into precompiles and EVM part
- Check if Go implementation of Keccak256 can be improved to match the speed of Rust (huge difference in performance in my tests)

**Comment by MadeofTin** [comment]
Updated for Friday. Can do Tuesday if enough people signal that works for them. @timbeiko @holiman /others who would like to be involved.

**Comment by shamatar** [comment]
Numbers for [2666](https://github.com/ethereum/EIPs/pull/2666) were updated. There is actually no large discrepancy for Keccak implementation. Also added hints to further reductions if implementations in Go and Rust could be brought closer in performance.

**Comment by shamatar** [comment]
[EIP2666](https://github.com/ethereum/EIPs/pull/2666) now also includes a proposal to uniform error, DDoS and gas handling by precompiles.
