### ISSUE TITLE
Eth1.x State-Network Call 0

### ISSUE THREAD

**Issue by MadeofTin** [ethereum/pm#194]
Date: Tuesday, July 14th 22 UTC

Agenda:

**Comment by lightclient** [comment]
Documents to discuss:

- https://notes.ethereum.org/g-npI1x7QRqoSzclvkLYzw
- https://ethresear.ch/t/state-network-use-cases/7634/9
- https://ethresear.ch/t/explorations-into-using-dht-skipgraph-for-chain-and-state-data-retrieval/7337/4

**Comment by MadeofTin** [comment]
Great call everyone 👍
