### ISSUE TITLE
YOLOv2 EIPs Discussion

### ISSUE THREAD

**Issue by timbeiko** [ethereum/pm#204]
# YOLOv2 EIPs Discussion

-   Meeting Date/Time:  **Monday 7 September 2020, [14:00 UTC](https://savvytime.com/converter/utc-to-germany-berlin-united-kingdom-london-ny-new-york-city-ca-san-francisco-china-shanghai-japan-tokyo-australia-sydney/14-00)**
-   Meeting Duration 1.5 hours
-   Zoom: https://consensys.zoom.us/j/97683842262

# Agenda
1. [EIP-2718: Typed Transaction Envelope ](https://eips.ethereum.org/EIPS/eip-2718)

**Comment by poojaranjan** [comment]
**Summary of the meeting**

- YOLO v1 EIPs may not be included in YOLO v2 (depending on discussion with clients who could not participate in YOLOv1)

- For YOLO V2, a list of EIPs going in are available at [ethereum/eth1.0-specs](https://github.com/ethereum/eth1.0-specs/projects/1#column-10680418) and those are
    - EIP-2565
    - EIP-2929

- EIP-2718: TBD 
     - no decision in absence of proposer
     - discussion to be continued in the next breakout meeting
     - tag Piper Merriam, Alexey, Tomasz, Vitalik in breakout-room

- EIP- 2718:TBD
    - AI: Micah will make the changes to the proposal that were discussed today (on Filix’s suggestion)

- Timeline for Yolo V2
    - No timeline decided but as per client team,
    - Geth -  1 week for implementation
    - Besu - 2 weeks for implementation
    - OE - looking into all four proposals, the timeline for implementation will be shared soon
    - Nethermind - No representative
    - TurboGeth - No representative

**Next breakout meeting** planned on Monday, Sep 14 at 1400 UTC.
