### ISSUE TITLE
Breakout-room discussion #4 (EIP-2711) Agenda

### ISSUE THREAD

**Issue by poojaranjan** [ethereum/pm#213]
## Date and Time
- Meeting Date/Time: Oct 9, 2020 1400 UTC
- Meeting Duration: 45 mins

## Location
Zoom: Will be shared in the breakout-room in EthR&D discord channel

## Agenda
- [EIP-2711: Sponsored, expiring and batch transactions](https://eips.ethereum.org/EIPS/eip-2711)
 - Discuss different approaches to new 2711-like tx functionality

**Comment by lightclient** [comment]
Additional documents:
* @axic's overview: https://notes.ethereum.org/@axic/Hyrc1i7ED#New-transaction-encoding
* @holiman's summary of the UNGAS breakage: https://ethresear.ch/t/counter-proposal-to-oil-karma-per-account-gas-limits/7433
* my discussion of the meta-tx problem: https://ethresear.ch/t/native-meta-transaction-proposal-roundup/7525

**Comment by axic** [comment]
Here's some notes from the call:  https://hackmd.io/CccouoTaRUu8gCrFPLB1fg

**Comment by poojaranjan** [comment]
### Summary
- It seems like the biggest desire to go with the rich transaction is to avoid mempool complexity of introducing batch transactions.
- At this point, there couldn't be a consensus on any transaction type that would be happily introduced in Berlin.
- Until the next upgrade or until there is agreement on the best mechanism, Lightclient will continue looking into the batch transaction understanding the complexity of mempool. 
- The **next meeting** to continue this discussion will be scheduled based on the suggestion in the Breakout room channel.

**Comment by poojaranjan** [comment]
The next meeting will be announced in the Eth R&D discord #breakout-room.
