### ISSUE TITLE
Breakout-room discussion #5 (EIP-2930, EIP-2972, EIP-2718) Agenda

### ISSUE THREAD

**Issue by poojaranjan** [ethereum/pm#223]
## Date and Time
- Meeting Date/Time: Nov 16, 2020 1500 UTC
- Meeting Duration: 60 mins

## Location
Zoom: Will be shared in the breakout-room in EthR&D discord channel

## Agenda

Transaction format specifics
- [EIP-2930: Optional access lists](https://eips.ethereum.org/EIPS/eip-2930)
 - [EIP-2972: Wrapped Legacy Transactions](https://eips.ethereum.org/EIPS/eip-2972)
- [EIP-2718: Typed Transaction Envelope](https://eips.ethereum.org/EIPS/eip-2718)

**Comment by RatanRSur** [comment]
This is my first breakout room, do we not create google calendar invites for this in addition to this?

**Comment by poojaranjan** [comment]
We do, please DM me your email on discord.

**Comment by poojaranjan** [comment]
Recording: [Breakout room #5](https://www.youtube.com/watch?v=aBVFOlwDD94&feature=youtu.be&t=5)
