### ISSUE TITLE
Eth1 -> Eth2 Merge Requirements Overview

### ISSUE THREAD

**Issue by mkalinin** [ethereum/pm#247]
The material to facilitate discussion around the Merge planned for ACD 106.

#### Spec drafts
- [[DRAFT] Beacon chain spec](https://hackmd.io/QFm6Ih_-Si6_kSLCWTZQyw)
- [[DRAFT] Eth1-Eth2 communication protocol](https://hackmd.io/T9x2mMA4S7us8tJwEB3FDQ?view)

#### Eth1 client modifications
  - eth1-eth2 communication protocol
  - state and chain sync
  - new opcodes (`RANDOM`, `BEACONBLOCKROOT`, etc)
  - block storage (block number, block hash, fork choice)
  - consensus part (ethash, difficulty, timestamp, rewards)

#### Breaking changes
  - `BLOCKHASH` opcode (either randomness or verification)
  - `DIFFICULTY` opcode
  - guarantee of storing entire block history by full nodes

**Comment by timbeiko** [comment]
Added to the agenda, thanks @mkalinin !

**Comment by mkalinin** [comment]
### Eth1 side changes

#### Client modifications
  - eth1-eth2 communication protocol
  - state sync
  - new opcodes (`RANDOM`, `BEACONBLOCKROOT`, etc)
  - block storage (block number, block hash, fork choice)
  - consensus part (ethash, difficulty, timestamp, rewards)
  - garbage collection

#### Breaking changes
  - `BLOCKHASH` (either randomness or verification)
  - block history _is not_ held by each node in the network anymore

**Comment by djrtwo** [comment]
Recent workshop presentations by @mkalinin  and @gballet on eth1/eth2 merge
https://www.youtube.com/watch?v=uGeIDNEwHjs&t=7450s

**Comment by holgerd77** [comment]
Argh, argh. Sorry for writing the same message over and over: but - also here - actually loved the fact that we finally had some dedicated issues on these things (HF timing, merge,...), would find it very valuable to keep this open (or - again - is there another go-to place here?). 😋
