### ISSUE TITLE
Proposal to include EIP 3300 (phase out refunds) in London

### ISSUE THREAD

**Issue by wjmelements** [ethereum/pm#258]
EIP here: ethereum/EIPs#3300

Hoping to discuss this in the ACD on 5 March. EIP 33000 can be discussed together with EIP 3298. I propose 3300 in London and 3298 in a subsequent HF.

Expected time: 15 minutes.

**Comment by timbeiko** [comment]
Added to the agenda to discuss alongside 3298.

**Comment by timbeiko** [comment]
@wjmelements added to the next call's agenda given how little time we had to discuss today: https://github.com/ethereum/pm/blob/master/README.md#acd-108-march-19-2021

**Comment by timbeiko** [comment]
Closing this as 3322 was considered the favored approach on ACD108.
