### ISSUE TITLE
CFI applied EIPs for London 

### ISSUE THREAD

**Issue by poojaranjan** [ethereum/pm#259]
Following the new [network upgrade process](https://medium.com/ethereum-cat-herders/shedding-light-on-the-ethereum-network-upgrade-process-4c6186ed442c), a few proposals have applied for [Consider For Inclusion (CFI)](https://github.com/ethereum/eth1.0-specs/projects/1#column-10680407) in [Eth1.0 spec repo](https://github.com/ethereum/eth1.0-specs/issues). 

Based on the author's response to EIP's readiness for the London upgrade, [the sheet](https://docs.google.com/spreadsheets/d/1yZsxoq5iBInI0zSdkw4TTdkZ8X3yVtneQC5nkRIk01Q/edit#gid=1214645356) shared in the last ACD meeting is updated. 

I'd be happy to go over the list to talk about the readiness status of the EIPs and propose them for the London upgrade.

**Comment by timbeiko** [comment]
Closing this as it seems like EIP champions for various London + Shanghai EIPs have stepped up. If others want their EIP to to be proposed/included, please open a specific issue related to your EIP.
