### ISSUE TITLE
ACD 80 listed incorrectly

### ISSUE THREAD

**Issue by lightclient** [ethereum/pm#265]
ACD 80 is listed to have occured on 24.1.2020 in the README, but it in fact [occurred](https://github.com/ethereum/pm/issues/150) on 7.2.2020.

**Comment by lightclient** [comment]
ACD 90 is also incorrect - listed as 12.6.2020, but was [actually](https://github.com/ethereum/pm/blob/master/All%20Core%20Devs%20Meetings/Meeting%2090.md) 26.6.2020.

**Comment by timbeiko** [comment]
Thanks for spotting, @lightclient 😄 Fixed.

**Comment by lightclient** [comment]
Thank you :)
