### ISSUE TITLE
Proposal to add EIP-3322 in London

### ISSUE THREAD

**Issue by wjmelements** [ethereum/pm#266]
EIP-3322 can be discussed as another alternative to EIP-3298 and EIP-3300. It should be discussable in the same 15-minute time frame.

https://github.com/ethereum/EIPs/pull/3322

**Comment by timbeiko** [comment]
@wjmelements added to the next call's agenda given how little time we had to discuss today: https://github.com/ethereum/pm/blob/master/README.md#acd-108-march-19-2021

**Comment by shemnon** [comment]
Adding 3 new opcodes and a 5th item to track with every account is too much for London.  If it were to target Shanghai we could discuss the merits, but the timeframe makes this a non-starter because of complexity.

**Comment by wjmelements** [comment]
> Adding 3 new opcodes and a 5th item to track with every account is too much for London. If it were to target Shanghai we could discuss the merits, but the timeframe makes this a non-starter because of complexity.

Please respect the `discussions-to` url https://ethereum-magicians.org/t/eip-3322-efficient-gas-storage/5470

**Comment by shemnon** [comment]
If I were to discuss the merits that would be a good target, but this is covering the question as to whether or not it should be considered for London, which is orthogonal to the actual content.

**Comment by wjmelements** [comment]
I was able to discussing timing in discussions-to URLs in the past; I
suspect you might also have such a capability.

**Comment by timbeiko** [comment]
Closing this because on ACD 108 (#288) it was deemed too complex for London by several client teams (and had some teams fully opposed). See conversation at [42:35](https://youtu.be/AclPXsRlgSc?t=2555). Other relevant conversations at 29:23, 30:52, 37:17 and 40:36.

**Comment by tuanggolt** [comment]
open
