### ISSUE TITLE
Proposal to specify Shanghai for October (3 months after London)

### ISSUE THREAD

**Issue by tkstanczak** [ethereum/pm#267]
This will open space for discussion on EIPs inclusion that will not delay the schedule of the much awaited London release.

**Comment by lightclient** [comment]
IMO, 3 months is too short of a window after London. As soon as London ships we need to immediately get another hard fork ready. I think January 2021 (~6 months after London) would be a better choice.

**Comment by timbeiko** [comment]
My hunch here is we should get a feel for what the big "feature" or "theme" of Shanghai would be before committing to a timeline. I think the amount of client work will end up dictating what a possible timeline is. 

We should perhaps set a maximum delay (using the difficulty bomb?) though. I suspect 6 months is probably the most we want to wait, but am open to others' opinion on this :-)

**Comment by timbeiko** [comment]
Noting one thing here: there have been many conversations about accelerating the Eth2 merge (i.e. @vbuterin's [recent doc](https://notes.ethereum.org/@vbuterin/B1mUf6DXO)). We should consider whether we want Shanghai to be focused on the merge, rather than having another "feature fork".

**Comment by holgerd77** [comment]
@timbeiko yeah, that's seems to be the right timing to me setting the merge as more or less the single focus for Shanghai, we definitely need some dedicated attention for this.

**Comment by timbeiko** [comment]
Issue related to this: https://github.com/ethereum/pm/issues/278

**Comment by gcolvin** [comment]
@timbeiko  Whether it comes before or after the merge, I think a clear candidate for a future "feature" fork is to pull together our outstanding EVM proposals into a coherent whole.

I've re-opened an EVM group on the [Magicians]( https://ethereum-magicians.org/t/evm-evolution-working-group-formation/3218/3) as a place to start on these and others.

* [EVM encapsulation format](https://notes.ethereum.org/@axic/evm-object-format)
* [EVM384](https://notes.ethereum.org/@poemm/evm384-update4)
* [List of EVM features potentially worth removing](https://hackmd.io/@vbuterin/evm_feature_removing)
* [EIP-3337: Frame pointer support for memory load and store operations](https://eips.ethereum.org/EIPS/eip-3337)
* [EIP-3336: Paged memory allocation for the EVM](https://eips.ethereum.org/EIPS/eip-3336)
* [EIP-2930: Optional access lists](https://eips.ethereum.org/EIPS/eip-2930)
* [EIP-2327: BEGINDATA](https://eips.ethereum.org/EIPS/eip-2327)
* [EIP-2315: Simple Subroutines for the EVM ](https://eips.ethereum.org/EIPS/eip-2315)
* [EIP-1153: Transient storage opcodes](https://eips.ethereum.org/EIPS/eip-1153)
* [EIP-1051: Overflow checking for the EVM](https://eips.ethereum.org/EIPS/eip-1051)
* [EIP-616: SIMD Operations for the EVM](https://eips.ethereum.org/EIPS/eip-616)
* [EIP-615: Subroutines and Static Jumps for the EVM](https://eips.ethereum.org/EIPS/eip-615)

**Comment by timbeiko** [comment]
Closing this because we agreed on ACD111 to start working on Shanghai as soon as London is done. We can open issues related to specific EIPs to be included in Shanghai 2-3 calls from now.
