### ISSUE TITLE
Statelessness & State Expiry Call

### ISSUE THREAD

**Issue by timbeiko** [ethereum/pm#268]
# Meeting Info
Date: March 8, 2021
Time: 14:00 UTC 
Duration: 60 minutes (+15 min potential overflow)
Zoom: https://consensys.zoom.us/j/92992767060

# Agenda
* Discussing the proposals laid out here: https://hackmd.io/@HWeNw8hNRimMm2m2GH56Cw/state_expiry_paths
* Please add more specific topics in the comments 😄

**Comment by diega** [comment]
Hi! will this recording be available?

**Comment by timbeiko** [comment]
@diega the recording is available here: 

https://consensys.zoom.us/rec/share/8YB6LjgZmmxx1je2Lkshgm3G6JH1-DAiJ3KHos3VNKUlwgTY92OCbsZWxEs4_F5i.ADL2eigLu4ac7LCg Passcode: 2%612?+L
