### ISSUE TITLE
Proposal to include EIP 2677 ( Limit size of `initcode`) in London

### ISSUE THREAD

**Issue by holiman** [ethereum/pm#271]
[EIP](https://eips.ethereum.org/EIPS/eip-2677)

Simple summary: Enforce a maximum size limit (max_initcode_size) of 49152 (0xc000) for initcode.

Cats: ![](http://4.bp.blogspot.com/_dedcXqzPdxo/TRTkwvgijKI/AAAAAAAABt4/SRz-CDS30F0/s1600/Cat_pictures2.jpg)

**Comment by timbeiko** [comment]
Added to the next call's agenda @holiman

**Comment by timbeiko** [comment]
From the ETH R&D discord: 

[Alexey, TurboGeth](https://discord.com/channels/595666850260713488/745077610685661265/820593549078822942):
>  Limiting size of initcode - I would say yes, this looks trivial but I would like to hear more about benefits

**Comment by shemnon** [comment]
I support.  I would feel better if there were some mainnet analytic support to show that we are not breaking too many transactions, and that mitigations by TX authors won't lead to state/code bloat. But I am persuaded by the security needs.

**Comment by timbeiko** [comment]
We agreed on ACD111 to not include this in London, so closing this.
