### ISSUE TITLE
Proposal to include EIP-3368 in London

### ISSUE THREAD

**Issue by timbeiko** [ethereum/pm#273]
@bitsbetrippin has authored [EIP-3368](https://eips.ethereum.org/EIPS/eip-3368) and [signaled on discord](https://discord.com/channels/595666850260713488/798586271445680129/819994852421927012) he would like to discuss its potential inclusion for London

**Comment by timbeiko** [comment]
From the ETH R&D discord: 

[Alexey, TurboGeth](https://discord.com/channels/595666850260713488/745077610685661265/820598687897485322):
> Regarding the EIP that increases mining reward and then tapers it off. I do not think most of core devs that join the call are necessarily "championing" EIP-1559, so it is a bit unfair to ask them to adjudicate political issues like that. Yes, it is political, and important issue, but not sure what is expected from Core Devs on the call? They cannot commit either way on behalf of all people who are for and against EIP-1559, so having this on ACD is just going to make everyone frustrated and disappointed. If they are looking for some kind of pronouncement from Hudson or Tim, this pronouncement can be made in a different place

**Comment by shemnon** [comment]
Personally I would oppose any increase to block reward (disclosure: tiny bags with a long term hold plan), I see only bad things happening with the Ethereum price if issuance goes up, and my instinct is that it would cause a downward trend in ether price this would impact miners more than the 1559 base-fee burn would.  I would want to hear from HODLers as well as someone with real market and economic experience to give assurance it wouldn't wind up making things worse for all stake holders, miners included.

**Comment by timbeiko** [comment]
Closing this as it was agreed to not include EIP-3368 in London on ACD108.
