### ISSUE TITLE
EIP-3403 - Partial Removal of Refunds

### ISSUE THREAD

**Issue by timbeiko** [ethereum/pm#277]
Another gas refund proposal by @vbuterin: https://github.com/ethereum/EIPs/pull/3403/

Related to #255 #258 & #266

**Comment by holiman** [comment]
Related:https://gist.github.com/holiman/aa7d2d28a9747548a0a14321a1572b22

**Comment by timbeiko** [comment]
We agreed on ACD111 to not have this in London, but rather consider the to-be-created alternative, so closing this.
