### ISSUE TITLE
Proposal to add EIP-2935 to Shanghai fork

### ISSUE THREAD

**Issue by tkstanczak** [ethereum/pm#279]
This EIP has been discussed on Peep an EIP: https://www.youtube.com/watch?v=QH5yuNd3B6o
https://eips.ethereum.org/EIPS/eip-2935

It improves our ability to deliver various stateless client constructions and provides opportunity for smart contracts to use fact about the past state (without requiring additional storage)

**Comment by tkstanczak** [comment]
Suspended until the Merge

**Comment by timbeiko** [comment]
@tkstanczak re-opening just so that we have the list of currently proposed EIPs as open issues to go over it once the merge work has progressed more :-)

**Comment by RatanRSur** [comment]
Where is the latest info about the history accumulator that could serve as an alternative to this? I'm interested to see how involved of a change that is

**Comment by timbeiko** [comment]
@tkstanczak note that on #616 we agreed to use Ethereum Magicians to discuss potential Shanghai EIPs async over the next few weeks. See [here](https://ethereum-magicians.org/t/shanghai-core-eip-consideration/10777/) for more info.

**Comment by holgerd77** [comment]
Can this be closed given the latest state from ACD yesterday?

**Comment by timbeiko** [comment]
We finalized the scope for Shanghai on ACD151, and discussions about Cancun inclusion should be moved to https://ethereum-magicians.org/t/cancun-eip-consideration/12060
