### ISSUE TITLE
For 109 agenda: EVM working group

### ISSUE THREAD

**Issue by gcolvin** [ethereum/pm#292]
@timbeiko  Whether it comes before or after the merge, I think a clear candidate for a future "feature" fork is to pull together our outstanding EVM proposals into a coherent whole.

I've re-opened an [EVM group on the Magician's]( https://ethereum-magicians.org/t/evm-evolution-working-group-formation/3218/3) as a place to start on these and others.

* [EVM encapsulation format](https://notes.ethereum.org/@axic/evm-object-format)
* [EVM384](https://notes.ethereum.org/@poemm/evm384-update4)
* [List of EVM features potentially worth removing](https://hackmd.io/@vbuterin/evm_feature_removing)
* [EIP-3337: Frame pointer support for memory load and store operations](https://eips.ethereum.org/EIPS/eip-3337)
* [EIP-3336: Paged memory allocation for the EVM](https://eips.ethereum.org/EIPS/eip-3336)
* [EIP-2930: Optional access lists](https://eips.ethereum.org/EIPS/eip-2930)
* [EIP-2327: BEGINDATA](https://eips.ethereum.org/EIPS/eip-2327)
* [EIP-2315: Simple Subroutines for the EVM ](https://eips.ethereum.org/EIPS/eip-2315)
* [EIP-1153: Transient storage opcodes](https://eips.ethereum.org/EIPS/eip-1153)
* [EIP-1051: Overflow checking for the EVM](https://eips.ethereum.org/EIPS/eip-1051)
* [EIP-616: SIMD Operations for the EVM](https://eips.ethereum.org/EIPS/eip-616)
* [EIP-615: Subroutines and Static Jumps for the EVM](https://eips.ethereum.org/EIPS/eip-615)

**Comment by tkstanczak** [comment]
EIP-2935

**Comment by timbeiko** [comment]
Closing this as it was discussed on ACD 109 - future conversation can happen on EthMagicians directly 🤹‍♂️
