### ISSUE TITLE
AllCoreDevs Meeting 9 Agenda

### ISSUE THREAD

**Issue by Souptacular** [ethereum/pm#3]
# All Core Devs Meeting 9 Agenda
### Meeting Duration 1.5 hours
# Agenda
Please provide comments to add or correct agenda topics.

0. Should we set up a set meeting time? The first and third Friday of every month at 14:00 UTC maybe? Given enough notice, we can push these meetings back or forward a week due to major events that multiple core devs will be attending (such as Edcon Feb. 14th).
1. Come to final agreement on [EIP5/8](https://github.com/ethereum/EIPs/issues/8) [Facilitator: Christian]
2. Precompiles for elliptic curve point addition, elliptic curve scalar multiplication and pairing [Facilitator: Christian]
3. Metropolis and associated EIPs. [Facilitator: Vitalik]
* https://github.com/ethereum/EIPs/issues/101 (bigint arithmetic)
* https://github.com/ethereum/EIPs/issues/140 ("cheap throw" by Nikolai)
* https://github.com/ethereum/EIPs/issues/100 (uncle mining incentive fix)
* https://github.com/ethereum/EIPs/issues/96 (putting block hashes and state roots into the state)
* https://github.com/ethereum/EIPs/issues/86 (abstraction)

4. New general state tests: https://github.com/ethereum/EIPs/issues/176 . [Facilitator: Martin S.]
5. STATIC_CALL: ethereum/EIPs#116 with additional points to discuss. [Facilitator: Christian]
Do we want three call variants:
(1) anything is possible (current call)
(2) state modifications are disallowed
(3) state modifications and state reads are disallowed (except for code) furthermore, do we want a special call opcode that fails if the target does not contain code?
6. [EIP 141: EVM opcode: designated invalid instruction](https://github.com/ethereum/EIPs/issues/141). [Facilitator: Christian]
7. Difficulty bomb block 3.5 mil. is < 3 months away. [Reference to previous calculations](https://www.reddit.com/r/ethereum/comments/4iozgf/in_around_14_month_the_difficulty_bomb_will_make/d30c0lq/). [Facilitator: Martin S.]
8. New EIP GitHub process and cleanup. [See details here](https://github.com/ethereum/EIPs/pull/183) [Facilitator: Hudson]

**Comment by chriseth** [comment]
- Come to final agreement on [EIP5/8](https://github.com/ethereum/EIPs/issues/8)
 - Precompiles for elliptic curve point addition, elliptic curve scalar multiplication and pairing

**Comment by holiman** [comment]
* New general state tests: https://github.com/ethereum/EIPs/issues/176 .

**Comment by chriseth** [comment]
- `STATIC_CALL`: https://github.com/ethereum/EIPs/issues/116 with additional points to discuss:
  - do we want three call variants: (1) anything is possible (current call) (2) state modifications are disallowed (3) state modifications and state reads are disallowed (except for code)
  - furthermore, do we want a special call opcode that fails if the target does not contain code?

**Comment by holiman** [comment]
How about https://www.reddit.com/r/ethereum/comments/4iozgf/in_around_14_month_the_difficulty_bomb_will_make/d30c0lq/ . It's less than three months left to block 3.5M . If I interpret it correctly, we should plan a HF somewhere within the coming couple of months.

**Comment by Souptacular** [comment]
Notes and audio posted to https://github.com/ethereum/pm/blob/master/All%20Core%20Devs%20Meetings/Meeting%209.md

Closing issue.
