### ISSUE TITLE
EIP-3074 Community Call 2

### ISSUE THREAD

**Issue by lightclient** [ethereum/pm#303]
# EIP-3074 Community Call 2
- Meeting Date/Time: Monday 26 April 2021, 16:00 UTC.
- Meeting Duration 1 hour
- Meeting link: https://us02web.zoom.us/j/83343120771?pwd=bW0wckdnUFdFTzE4SHZ2U0xvSXQ3dz09

## Agenda

The authors of EIP-3074 are hosting a call on to discuss the EIP. The goal of the call is to educate teams who will interface with the EIP directly (e.g. wallet and relayer teams), discuss various tradeoffs, and receive feedback on the proposal.

* EIP-3074 development updates
* [Puxi testnet](https://github.com/quilt/puxi)
* Future work
* Q&A

**Comment by poojaranjan** [comment]
Recording: https://youtu.be/pUJlZMXrVEI
