### ISSUE TITLE
Proposal to include EIP-3541 in London

### ISSUE THREAD

**Issue by axic** [ethereum/pm#307]
We propose to include [EIP-3541](https://github.com/ethereum/EIPs/pull/3541) in London (it is only an EIP PR right now, but hopefully gets merged in a few days).

This change is very simple itself and is the first step of the larger [EIP-3540](https://github.com/ethereum/EIPs/pull/3540), which we hope to have included in Shanghai.

It is important to consider 3541 for London, otherwise 3540 would be delayed to Cancun at earliest. We think including 3541 will not cause any delay to London, given its simplicity.

**Comment by timbeiko** [comment]
We agreed on ACD 112 to move EIP-3541 to CFI and decide about London inclusion on the following call. It's been updated in the [tracker board](https://github.com/ethereum/eth1.0-specs/projects/1#column-10680411).

**Comment by timbeiko** [comment]
Thanks, @axic. Added the proper commit in the [Baikal spec](https://github.com/ethereum/eth1.0-specs/blob/master/network-upgrades/client-integration-testnets/baikal.md).

**Comment by axic** [comment]
Thanks! Could you also change the link on the left hand side? It still points to the PR.

**Comment by timbeiko** [comment]
Good catch, done :+1:

**Comment by axic** [comment]
@timbeiko we have pushed unit tests into the EIP and the status was also updated to review. Perhaps you want to change the commit hash to include the tests, but the comprehensive test changes are in https://github.com/ethereum/tests/pull/835 anyway.

**Comment by timbeiko** [comment]
Updated in the [baikal spec](https://github.com/ethereum/eth1.0-specs/commit/fe6cae07fa95e39f9d23c3d3d81078d84727cd1d), @axic :+1:

**Comment by timbeiko** [comment]
Closing given we agreed to include this in London in https://github.com/ethereum/pm/issues/309
