### ISSUE TITLE
Testnet Stress Tests

### ISSUE THREAD

**Issue by timbeiko** [ethereum/pm#341]
When London is live on testnets, I think we should try and do a stress test where we fill ~100 blocks on the network with transactions to see how clients (and potentially infrastructure) can handle this. In order to have people monitor things, it may make sense to schedule this in advance so the time is known. 

@MariusVanDerWijden and @matkt have done such stress tests on Calaveras, so I assume the tooling could be re-used given sufficient ETH. I have >1M ETH on Ropsten + Goerli, which should suffice for a few rounds of 100 block tests across each network.

**Comment by matkt** [comment]
yes it should be doable for me . I'm also setting up a Besu miner on ropsten to be able to test Besu as a miner

**Comment by timbeiko** [comment]
@matkt stress-tested Ropsten extensively and nothing broke 🎉 . Here are a few charts that show the `baseFeePerGas` over time: 

![basefee](https://user-images.githubusercontent.com/9390255/123454149-1723d600-d595-11eb-9460-49e63ddcfe6c.png)
> `baseFeePerGas` over time on Ropsten since fork block. London sets the initial value at 1 gwei, large spikes up are the stress test, final spike down is when the spammer was shut down. 

![burn](https://user-images.githubusercontent.com/9390255/123454276-3b7fb280-d595-11eb-8ba8-7ca1485615fc.png)

> ETH burnt per block during the stress test. 


Will leave this issue open in case we decide to do a similar test either with several spammers in parallel, and/or on Goerli.

**Comment by timbeiko** [comment]
Gave an update on ACD117, closing.
