### ISSUE TITLE
Proposal to add EIP-2537 (BLS Precompile) to Shanghai

### ISSUE THREAD

**Issue by ineffectualproperty** [ethereum/pm#343]
During the London HF definition it was decided to delay the BLS precompile to a future hardfork in order to minimize complexity. Opening this issue to propose EIP-2537 for inclusion in Shanghai.

EIP Link: https://eips.ethereum.org/EIPS/eip-2537
London inclusion discussion: https://github.com/ethereum/pm/issues/269

**Comment by glitch003** [comment]
Just wanted to pipe up here and say that EIP-2537 would unlock a lot of cool use cases for a protocol we're building.  I know there is a lot going on with the eth2 merge, but we are patiently waiting for this precompile to make it in to a fork.  Any prioritization to add this in the next fork would be greatly appreciated.

**Comment by amitcz** [comment]
Any guess when this EIP 2537 is going to activate??

**Comment by ralexstokes** [comment]
i'm keen to get something like EIP 2537 into Shanghai -- most of the work was done during the London HF so assuming we can prioritize these precompiles amongst all the other work that needs to go into Shanghai, we could see them soon

**Comment by djrtwo** [comment]
Additionally, there are now a number of robust and well-tested implementations of the requisite bls12-381 curve operations in production. There was pushback on this a while back because teams were worried about rolling and managing their own crypto libs, but this is absolutely not needed today and would even likely be discouraged..

**Comment by emizzle** [comment]
> Additionally, there are now a number of robust and well-tested implementations of the requisite bls12-381 curve operations in production. There was pushback on this a while back because teams were worried about rolling and managing their own crypto libs, but this is absolutely not needed today and would even likely be discouraged..

@djrtwo I can't seem to find the implementations mentioned. Could you kindly point me to a few of these implementations please?

**Comment by PeterCCLiu** [comment]
Pairing-based cryptography is the foundation to many fantastic constructions, and no doubt BLS12-381 is more secure than the existing BN128 precompile. Adding it not only can unlock many new use cases but can also enable new cryptograhic schemes that increase the security and privacy of many different scenarios. 

Adding it ASAP is highly significant and it's actually to Ethereum's advantage to be the underlying infrastructure of these new schemes and use cases. Would like to join the next core dev's call to advocate the progress of this EIP.

**Comment by ralexstokes** [comment]
@emizzle I think he is referring to the several production-grade consensus clients that use BLS operations for all of their signature operations -- many of them use this library: https://github.com/supranational/blst

**Comment by timbeiko** [comment]
@PeterCCLiu we decided a few calls ago to stop discussing inclusion of EIPs for future hard forks until we're a bit farther along with the merge work. If you have a technical update you want to give about the EIP, it's totally fine to discuss that on the call, but if you want to make a case for it to be included in Shanghai, we're probably a few calls still from thinking through that.

**Comment by PeterCCLiu** [comment]
> @PeterCCLiu we decided a few calls ago to stop discussing inclusion of EIPs for future hard forks until we're a bit farther along with the merge work. If you have a technical update you want to give about the EIP, it's totally fine to discuss that on the call, but if you want to make a case for it to be included in Shanghai, we're probably a few calls still from thinking through that.

Thank you Tim. Totally understand the situation here. I would just like to update the technical status of the EIP as of May 2022 to our community during ACD call -- it will be a short one. Please refer to the summary listed [here](https://ethereum-magicians.org/t/eip-2537-bls12-precompile-discussion-thread/4187/21).

**Comment by timbeiko** [comment]
@ineffectualproperty note that on #616 we agreed to use Ethereum Magicians to discuss potential Shanghai EIPs async over the next few weeks. See [here](https://ethereum-magicians.org/t/shanghai-core-eip-consideration/10777/) for more info.

**Comment by timbeiko** [comment]
This EIP was moved to CFI on ACD150, will close this issue.
