### ISSUE TITLE
Proposal to add EIP 3651 (Warm COINBASE) to Shanghai

### ISSUE THREAD

**Issue by wjmelements** [ethereum/pm#357]
Small change.

EIP Link: https://eips.ethereum.org/EIPS/eip-3651

**Comment by timbeiko** [comment]
@wjmelements thanks for sharing. I added it to https://github.com/ethereum/pm/issues/356, which is the higher level conversation we need to have about if and how we have a Shanghai before we decide what would be included in it. 

Would you like to take a couple minutes on the next call to present the proposal?

**Comment by wjmelements** [comment]
> @wjmelements thanks for sharing. I added it to #356, which is the higher level conversation we need to have about if and how we have a Shanghai before we decide what would be included in it.
> 
> Would you like to take a couple minutes on the next call to present the proposal?

Yes

**Comment by timbeiko** [comment]
On ACD133 we agreed to move this EIP to CFI for Shanghai. Commit: https://github.com/ethereum/execution-specs/commit/ded8ebeb9d79fe4729efe10b0b5e5c211eaa39c1

Closing this issue for now, we can re-open if any issues come up.
