### ISSUE TITLE
EIP-1559 Coordination Call (Breakout #11)

### ISSUE THREAD

**Issue by tvanepps** [ethereum/pm#363]
[Link to recording](https://youtu.be/r37ShBRdVDg)
Notes coming soon

---

## Date and Time
Date/Time: Friday, July 30 at 14:00 UTC (10:00 ET)
Duration: 60 mins

We will use this time to cover any outstanding discussion on EIP-1559 from the ecosystem perspective, including dev tooling and clients. 

⭐ [1559 JSON RPC Changes](https://hackmd.io/@timbeiko/1559-json-rpc)
⭐ [Ecosystem Readiness Tracker](https://github.com/ethereum/eth1.0-specs/blob/master/network-upgrades/ecosystem-readiness.md)
⭐ [1559 Cheatsheet for Implementers](https://hackmd.io/4YVYKxxvRZGDto7aq7rVkg?view)

## Agenda
- Presentation from Ecosystem Tooling
- Wallet Demos
- "Require `gasPrice`" discussion, expected deprecation ([previous discussion here](https://github.com/ethereum/eth1.0-specs/pull/251#issuecomment-881182475))
- [Ethereum Roadmapping Improvements](https://ethereum-magicians.org/t/ethereum-roadmapping-improvements/6653/12?u=timbeiko)
- Open Discussion

↓ Leave a comment to add a topic to open discussion ↓

**Comment by BakeryD** [comment]
*July 30th ?

**Comment by timbeiko** [comment]
@BakeryD good catch, thanks! edited :+1:

**Comment by timbeiko** [comment]
Definitely not the most important thing, but if time permit, I'd be curious to get feedback from infrastructure providers on https://ethereum-magicians.org/t/ethereum-roadmapping-improvements/6653/12?u=timbeiko

**Comment by lightclient** [comment]
Might also be worth noting that go-ethereum `v1.10.7` will have a breaking change for `eth_feeHistory`: https://github.com/ethereum/go-ethereum/pull/23239

**Comment by timbeiko** [comment]
If wallets support EIP-1559 or plan to at launch, the ethereum.org website would like to note that: https://github.com/ethereum/ethereum-org-website/issues/2715#issuecomment-889584061

**Comment by timbeiko** [comment]
Closed in favor of https://github.com/ethereum/pm/issues/369

**Comment by dechapon25** [comment]
[Link to recording](https://youtu.be/r37ShBRdVDg)
Notes coming soon

---

## Date and Time
Date/Time: Friday, July 30 at 14:00 UTC (10:00 ET)
Duration: 60 mins

We will use this time to cover any outstanding discussion on EIP-1559 from the ecosystem perspective, including dev tooling and clients. 

⭐ [1559 JSON RPC Changes](https://hackmd.io/@timbeiko/1559-json-rpc)
⭐ [Ecosystem Readiness Tracker](https://github.com/ethereum/eth1.0-specs/blob/master/network-upgrades/ecosystem-readiness.md)
⭐ [1559 Cheatsheet for Implementers](https://hackmd.io/4YVYKxxvRZGDto7aq7rVkg?view)

## Agenda
- Presentation from Ecosystem Tooling
- Wallet Demos
- "Require `gasPrice`" discussion, expected deprecation ([previous discussion here](https://github.com/ethereum/eth1.0-specs/pull/251#issuecomment-881182475))
- [Ethereum Roadmapping Improvements](https://ethereum-magicians.org/t/ethereum-roadmapping-improvements/6653/12?u=timbeiko)
- Open Discussion

↓ Leave a comment to add a topic to open discussion ↓
