### ISSUE TITLE
Add EIP-2981 as ERC

### ISSUE THREAD

**Issue by VexyCats** [ethereum/pm#366]
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-2981.md EIP-2981 has been marked as final.

**Comment by timbeiko** [comment]
@VexyCats I'm not sure what the goal of this issue is? If the EIP is final, it will show [here](https://eips.ethereum.org/erc) in the "Final" section, and it does. Closing, but please reopen if you have another concern.

**Comment by Zachinquarantine** [comment]
I think @VexyCats **may** have been asking if [EIP-2981 could be included in Shanghai](https://github.com/ethereum/EIPs/issues/2907#issuecomment-886242018), but idk

**Comment by timbeiko** [comment]
ERCs are not included in hard forks: anyone can use them at any time, they don't need to "go live" at a specific block like consensus changes do.

**Comment by Zachinquarantine** [comment]
👌🏻
