### ISSUE TITLE
Post London EIP-1559 Assessment (Breakout #12)

### ISSUE THREAD

**Issue by tvanepps** [ethereum/pm#369]
## Date and Time
Date/Time: Friday, Aug 13 at 14:00 UTC (10:00 ET)
Duration: 60 mins

Post-London discussion and assessment of EIP-1559 for implementers, tooling, and infrastructure providers.

## Agenda
- Overview from Tim on how the upgrade went
- General London feedback from attendees - how should this experience inform the path towards the Merge?
- Presentation from Barnabé Monnot on the data so far
- Wallets best practices (UI, UX)
- Reducing wallet / API tip overpayment (1-2 gwei should be fine)
- geth [1.10.7 release](https://github.com/ethereum/go-ethereum/pull/23239)
- Library adjustments, if any
- What's next for 1559, what to track

⭐ [1559 JSON RPC Changes](https://hackmd.io/@timbeiko/1559-json-rpc)
⭐ [Ecosystem Readiness Tracker](https://github.com/ethereum/eth1.0-specs/blob/master/network-upgrades/ecosystem-readiness.md)
⭐ [1559 Cheatsheet for Implementers](https://hackmd.io/4YVYKxxvRZGDto7aq7rVkg?view)

↓ Leave a comment to add a topic to open discussion ↓

**Comment by timbeiko** [comment]
Two things I'll put here to not forget:

1. I think wallets are probably overestimating the priority fee they are suggesting for users. In my experience, 1 gwei gets you included in ~1 min, 2 gwei was in the next 1-2 blocks, and at that time, wallets were suggesting 10-30 gwei. 

2. It would be good to get folks' feedback about London in general and what we could improve for the merge in the coming months. When do they want to start getting pinged? When do they expect to add support? What resources do they want? etc.

**Comment by timbeiko** [comment]
Recording of the call: https://youtu.be/ZmzIHFuwdg0
