### ISSUE TITLE
The Merge: Engine API design space Call 2

### ISSUE THREAD

**Issue by mkalinin** [ethereum/pm#385]
## Date and Time

Date/Time: [Thursday, Sept 9 at 13:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20210909T130000&p1=1440&p2=224&p3=179&p4=195&p5=237)
Duration: 60 mins
Zoom: to be shared in Ethereum R&D discord before call.

## Agenda

Continue discussion on [Engine API design space](https://hackmd.io/@n0ble/consensus_api_design_space):
* Briefly cover changes in the [Minimal set of methods](https://hackmd.io/@n0ble/consensus_api_design_space#Minimal-set-of-methods) section that have been added since [ACD 121](https://github.com/ethereum/pm/issues/379)
* Proceed with the [Transition process](https://hackmd.io/@n0ble/consensus_api_design_space#Transition-process) section

**Comment by timbeiko** [comment]
Recording for the call: https://youtu.be/uAT-xkRVicQ
