### ISSUE TITLE
Proposal to include EIP-3756: Gas Limit Cap

### ISSUE THREAD

**Issue by lightclient** [ethereum/pm#389]
https://eips.ethereum.org/EIPS/eip-3756
https://ethereum-magicians.org/t/eip-3756-gas-limit-cap/6921

**Comment by timbeiko** [comment]
@lightclient note that on #616 we agreed to use Ethereum Magicians to discuss potential Shanghai EIPs async over the next few weeks. See [here](https://ethereum-magicians.org/t/shanghai-core-eip-consideration/10777/) for more info.

**Comment by timbeiko** [comment]
We finalized the scope for Shanghai on ACD151, and discussions about Cancun inclusion should be moved to https://ethereum-magicians.org/t/cancun-eip-consideration/12060
