### ISSUE TITLE
Enshrine EIP-3607: Reject transactions from senders with deployed code

### ISSUE THREAD

**Issue by yperbasis** [ethereum/pm#390]
[EIP-3607](https://eips.ethereum.org/EIPS/eip-3607) is already merged to geth (https://github.com/ethereum/go-ethereum/pull/23303). Let's move the EIP to Final and update the Yellow Paper (https://github.com/ethereum/yellowpaper/pull/801) to formally enshrine it.

**Comment by timbeiko** [comment]
We agreed on ACD124 to move this to Final.
