### ISSUE TITLE
Proposal to include EIP-3074 in Shanghai

### ISSUE THREAD

**Issue by lightclient** [ethereum/pm#394]
https://eips.ethereum.org/EIPS/eip-3074

--

### Description

Allow externally owned accounts (EOAs) to delegate control of their account to a contract.

This EIP introduces two EVM instructions AUTH and AUTHCALL. The first sets a context variable authorized based on an ECDSA signature. The second sends a call as the authorized. This essentially delegates control of the EOA to smart contract.

**Comment by timbeiko** [comment]
We finalized the scope for Shanghai on ACD151, and discussions about Cancun inclusion should be moved to https://ethereum-magicians.org/t/cancun-eip-consideration/12060
