### ISSUE TITLE
Metropolis Plan Discussion

### ISSUE THREAD

**Issue by Souptacular** [ethereum/pm#4]
# NOTE: OUTDATED. Please see: https://github.com/ethereum/EIPs/blob/master/README.md for latest accepted EIPS.

# Metropolis Discussion
Use this issue for discussion around Metro. I will update chart/todo list as comments come in.

Approximate ice age start (according to Vitalik):
  - Around March 25th (3 months) - Block time is 15.2 sec.
  - Around July 25th (6 months) - Block time is 29.7 sec.

## Metropolis Todo
- [ ] Decide which EIPs will potentially be in Metro (by way of EIP acceptance)
- [ ] Based on chart, decide which EIPs can fit into metro and which ones will not
- [ ] Pick a block number for Ropsten/Mainnet Metropolis

## EIP Implementation Chart
**Note: The EIPs listed in the chart **are not** necessarily approved for Metro via the EIP acceptance process, but we want to get information as early as possible.**

Client | [EIP 5/8](https://github.com/ethereum/EIPs/issues/8) | [EIP 86](https://github.com/ethereum/EIPs/issues/86) | [EIP 100](https://github.com/ethereum/EIPs/issues/100) | [EIP 101](https://github.com/ethereum/EIPs/issues/101) | [EIP 166](https://github.com/ethereum/EIPs/issues/166) | EIP [196](https://github.com/ethereum/EIPs/issues/196) & [197](https://github.com/ethereum/EIPs/issues/197) | EIP [206](https://github.com/ethereum/EIPs/pull/206) & [207](https://github.com/ethereum/EIPs/pull/207)
------------ | ------------- | ------------ | ------------- | ------------- | ------------ | ------------- | ------------
go-ethereum | :heavy_multiplication_x: | :heavy_multiplication_x: | :heavy_multiplication_x: | :heavy_multiplication_x: | :heavy_multiplication_x: | :heavy_multiplication_x: | :heavy_multiplication_x: |
Parity | :heavy_multiplication_x: | :heavy_multiplication_x: | :heavy_multiplication_x: | :heavy_multiplication_x: | :heavy_multiplication_x: | :heavy_multiplication_x: | :heavy_multiplication_x: |
cpp-ethereum | :heavy_multiplication_x: | :heavy_multiplication_x: | :heavy_multiplication_x: | :heavy_multiplication_x: | :heavy_multiplication_x: | :heavy_multiplication_x: | :heavy_multiplication_x: |
pyethapp | :heavy_multiplication_x: | :heavy_multiplication_x: | :heavy_multiplication_x: | :heavy_multiplication_x: | :heavy_multiplication_x: | :heavy_multiplication_x: | :heavy_multiplication_x: |
ethereumjs-lib | :heavy_multiplication_x: | :heavy_multiplication_x: | :heavy_multiplication_x: | :heavy_multiplication_x: | :heavy_multiplication_x: | :heavy_multiplication_x: | :heavy_multiplication_x: 
Ethereum(J) | :heavy_multiplication_x: | :heavy_multiplication_x: | :heavy_multiplication_x: | :heavy_multiplication_x: | :heavy_multiplication_x: | :heavy_multiplication_x: | :heavy_multiplication_x: |
ruby-ethereum | :heavy_multiplication_x: | :heavy_multiplication_x: | :heavy_multiplication_x: | :heavy_multiplication_x: | :heavy_multiplication_x: | :heavy_multiplication_x: | :heavy_multiplication_x: |

**Comment by romanman** [comment]
![image](https://cloud.githubusercontent.com/assets/5822633/22344305/5b241a2c-e404-11e6-8080-433436115b0a.png)
 
you have double Parity there

**Comment by Souptacular** [comment]
Thanks Roman!

**Comment by kumavis** [comment]
@Souptacular not "ethereumjs-lib" just "ethereumjs"

**Comment by kumavis** [comment]
> Note: The EIPs listed in the chart are not necessarily approved for Metro via the EIP acceptance process, but we want to get estimates as early as possible.
@Souptacular as possible it would be great to have the EIPs ordered by likelyhood of them being included in the next feature fork

**Comment by Souptacular** [comment]
That's a great idea. I currently do not have enough knowledge of the EIPs and their discussion history to make that call. It would be great if someone else could.

**Comment by Nashatyrev** [comment]
https://github.com/ethereum/EIPs/issues/166 : why do we need another replay protection?

**Comment by obscuren** [comment]
go-ethereum `[metropolis](https://github.com/ethereum/go-ethereum/labels/metropolis)` progress

**Comment by Souptacular** [comment]
@Nashatyrev Please ask in the the EIP Issue page for #166 and tag @vbuterin

**Comment by Souptacular** [comment]
The chart has been updated to correct some inaccurate potential EIPs.

**Comment by pirapira** [comment]
@Souptacular does it make sense to add "yellowpaper" as a client in the chart?

**Comment by mrstormlars** [comment]
What about delaying the diff.bomb and eventually decrease inflation (EIP#186/#189)? The Eth-community should have a possibility to vote on this.

**Comment by tawaren** [comment]
Is their any plan to include a byte code / EVM versioning scheme like #154 in Metropolis?
