### ISSUE TITLE
The Merge Community Call #1

### ISSUE THREAD

**Issue by tvanepps** [ethereum/pm#402]
## Date and Time
Friday, Nov 5 at 14:00 UTC (10:00 ET)
Duration: 60 mins

The first Merge Community call! Attendance is completely optional, we're hoping to get questions from Wallets, Apps, Explorers, Infra Providers surfaced early. 

If you are work in any of these groups, please DM me to be added to the calendar invite!

## Agenda
- Summary on the state of things
- [EIP-4399](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-4399.md)
- [Kintsugi](https://notes.ethereum.org/@djrtwo/kintsugi-milestones)
- Update on Pithos testnet
- [Merge Client architectures post](https://hackmd.io/@timbeiko/acd/https%3A%2F%2Ftim.mirror.xyz%2FsR23jU02we6zXRgsF_oTUkttL83S3vyn05vJWnnp-Lc) from Tim
- What applications and smart contract devs can expect to change (alpha leak, almost nothing 😄)
- Open Discussion

↓ Leave a comment to add a topic ↓

**Comment by timbeiko** [comment]
A few things that are worth discussing: 

* [Kintsugi 🍵](https://notes.ethereum.org/@djrtwo/kintsugi-milestones) office hours
* [EIP-4399](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-4399.md)

**Comment by ybstaked** [comment]
Can you please add public links for calendar invite and call link, so we don't have to track it down with DM messages? Thank you!

**Comment by afmsavage** [comment]
> @viktorbunin do you mean something like this? https://savvytime.com/converter/utc-to-germany-berlin-united-kingdom-london-ny-new-york-city-ca-san-francisco-china-shanghai-japan-tokyo-australia-sydney/nov-5-2021/2pm

I think Viktor and others are asking for a public calendar invite where they can add these to their calendar and not miss em.  Might be a good thing to ask the cat herders.

**Comment by tvanepps** [comment]
> Can you please add public links for calendar invite and call link, so we don't have to track it down with DM messages? Thank you!

public call links sometimes lead to events getting too large or spammed. we'll probably keep many of these invite only for now, but anyone can get added to the invite if the topic is relevant to them

**Comment by newmokha** [comment]
Add me to calendar invite
