### ISSUE TITLE
Proposal to include EIP-4399 to the Merge

### ISSUE THREAD

**Issue by mkalinin** [ethereum/pm#410]
[EIP-4399](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-4399.md) proposes to supplant `DIFFICULTY` opcode with `RANDOM` opcode that returns the output of the randomness beacon provided by the beacon chain.

This EIP is important to be included into the scope of the Merge as it allows to avoid breaking changes with respect to the way the `DIFFICULTY` opcode is utilized today. Namely, return value of the `DIFFICULTY` opcode accompanied with other inputs is used by smart contracts as a common pattern to get randomness. As the number of the opcode stays the same this EIP prevents backward incompatibilities on the EVM byte code level which means that existing smart contracts that utilize `DIFFICULTY` to obtain randomness won't be broken.

Additionally, a beacon chain randomness is exposed in the EVM. Outputs of the beacon chain randomness should be considered as a more strong outputs than either the difficulty or the block hash of the PoW network.

**Comment by djrtwo** [comment]
Excellent!

As this has been discussed many times on prior calls and in-person sessions, we'll be moving forward with this as additive to 3675 in November's Merge development milestones and devnets.

Obviously, if an unforeseen issue arises at the meeting in a couple of weeks, we can remove.

**Comment by timbeiko** [comment]
Closing this issue as this is now part of the [EL merge spec](https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/merge.md)
