### ISSUE TITLE
Proposal to Include EIP-4488 in the Shanghai Hard Fork

### ISSUE THREAD

**Issue by adietrichs** [ethereum/pm#437]
[Link to the EIP](https://eips.ethereum.org/EIPS/eip-4488)

Decrease transaction calldata gas cost, and add a limit of how much total transaction calldata can be in a block.

**Comment by adietrichs** [comment]
Auxiliary analysis looking into the effects of different mining strategies and stipend sizes on miner profitability: https://hackmd.io/@adietrichs/4488-mining-analysis

**Comment by timbeiko** [comment]
@adietrichs  note that on #616 we agreed to use Ethereum Magicians to discuss potential Shanghai EIPs async over the next few weeks. See [here](https://ethereum-magicians.org/t/shanghai-core-eip-consideration/10777/) for more info.

**Comment by timbeiko** [comment]
Closing this because 4844 has been CFI'd instead.
