### ISSUE TITLE
Proposal to include EIP-1153 in Shanghai

### ISSUE THREAD

**Issue by moodysalem** [ethereum/pm#438]
https://eips.ethereum.org/EIPS/eip-1153

For [this particular use case](https://ethereum-magicians.org/t/eip-1153-transient-storage-opcodes/553/45?u=moodysalem), it would be great to have it in the next hard fork.

[EIP-3529](https://eips.ethereum.org/EIPS/eip-3529) included in London is a regression for transient storage in that it greatly increased its practical gas cost. To prevent future hard forks from making transient storage significantly more expensive or breaking the use case, it's important to create these new opcodes for the specific use case of transient storage.

**Comment by timbeiko** [comment]
Arbitrum says they'd also benefit from this: https://ethereum-magicians.org/t/eip-1153-transient-storage-opcodes/553/47?u=fredlacs

**Comment by wbl** [comment]
We're very interested at Sealance in this, and I'm happy to help out with implementing, spec review, or whatever else needs to doing to make this a reality.

**Comment by timbeiko** [comment]
Lots of discussion about 1153 in https://github.com/ethereum/pm/issues/500

**Comment by moodysalem** [comment]
Project board tracking implementation progress:
https://github.com/orgs/Uniswap/projects/24

**Comment by timbeiko** [comment]
Closing this issue given 1153 was moved to CFI in https://github.com/ethereum/pm/issues/652
