### ISSUE TITLE
Consensus-layer Call 79

### ISSUE THREAD

**Issue by timbeiko** [ethereum/pm#443]
# Consensus-layer Call 79 Agenda
[prev: call 78](https://github.com/ethereum/pm/issues/439)

Meeting Date/Time: Thursday 2022/1/13 at 14:00 GMT 
Meeting Duration 1.5 hours 
[Live stream](https://youtu.be/izyYW9-HbNk)

1. [Kintsugi](https://notes.ethereum.org/@djrtwo/kintsugi-milestones) office hours
    * Kintsugi fiinalizing!
    * Update on testing
    * EL/engine-api handling of branching tips/reorgs
2. Other client updates (if any)
3. Research, spec, etc
4. Open Discussion/Closing Remarks

**Comment by benjaminion** [comment]
Quick notes: https://hackmd.io/@benjaminion/ryBR2ip3Y (glossing over some of the deeper technical discussion).
