### ISSUE TITLE
EIP-4444 Breakout 2 

### ISSUE THREAD

**Issue by lightclient** [ethereum/pm#454]
## Date and Time

Meeting Date/Time: Tuesday Jan 11 at 15:30 UTC
Meeting Duration: 30 mins

## Location

Zoom: https://consensysmesh.zoom.us/j/98265350520?pwd=ZlpKWVJjbDdPdEw5cUhVeGtpNzBudz09

#### Roadmap (discuss)
- Define SSZ object that will contain serialized block bodies
- Implement verification / import / export functionality in an execution client
- Distribute data over bittorrent
- Implement EIP-4444 in client to stop propagating historical data

#### Questions
- Advantages of SSZ vs. RLP?
- What compression format should be used?
- Should transactions and uncles be stored in separate objects?
- What should the process be to contribute to sharing data over bittorrent?

**Comment by lightclient** [comment]
Recording: https://consensysmesh.zoom.us/rec/share/ctLBx6rcO_CI4UybXktAfU1FN-iZtqtVc5NOdxlSUiDbX6L4mIjMjZgiv0aF-H85.mss3pp4rPfNZ8YVv Passcode: ?4SE4WC#

**Comment by poojaranjan** [comment]
Recording on YouTube - https://youtu.be/Kv2gbgBzQzg
