### ISSUE TITLE
Feb 4 ACD call not listed in README under "previous meetings"

### ISSUE THREAD

**Issue by cyrusadkisson** [ethereum/pm#478]
Also, where does the information about upcoming calls live? Can this be in the README as well?

**Comment by timbeiko** [comment]
> Feb 4 ACD call not listed in README under "previous meetings"

The PR hasn't been merged yet, see: https://github.com/ethereum/pm/pull/474

> Also, where does the information about upcoming calls live?

See the Issues tab, here's the latest call, which backlinks to the previous ones: https://github.com/ethereum/pm/issues/472 

> Can this be in the README as well?

From the [REAMDE](https://github.com/ethereum/pm#agendas) 😄 : 

    > The agendas for the calls are tracked in the Issues tab of this repository, under the "agenda" label (link).
