### ISSUE TITLE
Kurtosis Testing Breakout Room

### ISSUE THREAD

**Issue by timbeiko** [ethereum/pm#482]
### Meeting Info

Date: Friday Feb 25th, 14:00 UTC
Zoom: https://ethereumfoundation.zoom.us/j/89401092702?pwd=VVROV2FZYllraXQ5REx5d2hPcUlYdz09

### Agenda

* Kurtosis Overview
* Q&A

**Comment by timbeiko** [comment]
From the ACD 132 agenda: 

> I'd love to briefly present the work we've been doing with Kurtosis among all the client teams to help test the merge with local and CI-ready multi-client testnets. I'd also love to invite folks to join an information session in a couple weeks (will discuss details in meeting).

> Brief info:
[Docs on Kurtosis + The Merge](https://notes.ethereum.org/@ExXcnR0-SJGthjz1dwkA1A/H11OzhRAK)
[General Kurtosis docs](https://docs.kurtosistech.com)

**Comment by poojaranjan** [comment]
Recording: https://youtu.be/yMe4RG5emx8
