### ISSUE TITLE
EL Merge Client Release Naming Breakout Room

### ISSUE THREAD

**Issue by timbeiko** [ethereum/pm#491]
### Meeting Info 

* [March 11, 2022, 14:00 UTC](https://savvytime.com/converter/utc-to-germany-berlin-united-kingdom-london-ny-new-york-city-ca-san-francisco-china-shanghai-japan-tokyo-australia-sydney/mar-11-2022/2pm)
* Duration: 60 minutes
* Zoom: https://us02web.zoom.us/j/84728943195?pwd=UEdFUE5CR05qeHpsRkYxK1BsVEpGdz09

### Agenda

* Agree to a name for the EL client releases which enable the features for The Merge
* Previous discussion: https://ethereum-magicians.org/t/el-merge-client-release-naming/7928/16

**Comment by abcoathup** [comment]
🇫🇷
2 votes for Paris as first large non-Devcon conference
https://twitter.com/evan_van_ness/status/1479521576404062212

Unfortunately neither myself nor Evan can attend due to the time of the call.

**Comment by poojaranjan** [comment]
People can also participate in Twitter poll to vote for favorite name - 
https://twitter.com/EthCatHerders/status/1501924903804669958
