### ISSUE TITLE
Ideas for debug tools

### ISSUE THREAD

**Issue by parithosh** [ethereum/pm#520]
During devconnect we had a tooling session, the outcome of the session was a preliminary list of debug tools as well as a compilation of existing tools different client teams use. 

The list can be found [here](https://notes.ethereum.org/@parithosh/HJQDsoRr5)

The aim of this issue is to track the missing debug tools/debug functionality in clients as well as compile more ideas. If any tool is already being worked on, please link it in the comments or edit the issue so we can avoid duplicate work. 

- [ ] Dump CL beacon state + bad block encountered to disk (potentially as a flag in a CL node)
- [ ] Intermediate state roots
- [ ] Trace block (by RLP)
- [ ] Pause/Flush state (To prevent pruning of older state by clients)
- [ ] EL block <> CL slot mapper (to be able to co-relate blocks and slots more easily)
- [ ] Logging level by module (ideally modifiable in a client via RPC)
- [ ] Get block receipt RLP encoded
- [ ] Dump all invalid blocks/non de-serializable content received via gossip into disk (potentially as a flag in CL node)
- [ ] Aggregation of debug tools/flags every client team has + undocumented debug flags
- [ ] Incidence response doc for EL/CL team (So they know what initial data to collect that is useful for the others)
- [ ] Peer score dump (potentially with reason for downscoring)

Tagging @marioevz @mariusVanDerWijden @holiman @fredriksvantes  for visibility 

EDIT: Some of the above requests are also being tracked here: https://github.com/ethereum/go-ethereum/issues/24720

**Comment by timbeiko** [comment]
@parithosh any objections to closing this here given the staleness + it being tracked on the geth repo?

**Comment by parithosh** [comment]
Nope, no objections to that!
