### ISSUE TITLE
Ropsten beacon chain

### ISSUE THREAD

**Issue by djrtwo** [ethereum/pm#525]
We need to launch a Ropsten beacon chain to handle the merge of that testnet.

In our last CL call, it was [generally decided](https://hackmd.io/@benjaminion/Hy_VXLb8q#Ropsten-Beacon-Chain-launch) that Ropsten should be unpermissioned but for devs to have the majority of validators (similar to prater/goerli).

So this would entail
* deciding on a genesis validator set size and genesis time
* creating a genesis state with well-distributed validators across EL teams, CL teams, EF and launching the chain soon (before end of may)

I suggest we do 100k vals. This is reasonably resistant to disruptions due to external deposits in the near-term, and it seems likely Ropsten is deprecated not too far out after it's merge

**Comment by timbeiko** [comment]
Another thing to note is that we should have good documentation (and ideally faucets) for stakers who want to launch validators before The Merge on Ropsten to make sure their setup works as expected.

**Comment by parithosh** [comment]
As discussed on ACD, Ropsten will have a validator set of ~100k. I'd say 10000 validator keys per entity taking part (Assuming that every client team wants to take part) => Validator set of 110012 (9 client teams + EF + Attestant/Vouch + 12 for EF security).

If there are entities outside of client teams that would like to take part, please comment below.

I propose genesis for the ropsten beaconchain on 30th of May (~2.5 weeks from now). That should give us enough time for clients to have releases, blogposts to come out, explorers to be setup. At the same time, it would be an overlap of ~1 week before the proposed merge with Ropsten PoW chain. If we have altair + bellatrix happening in quick succession, the beaconchain would be ready well in advance.

**Comment by 0xWildhare** [comment]
> If there are entities outside of client teams that would like to take part, please comment below.

do i count as an entity

**Comment by parithosh** [comment]
@0xWildhare If you have a reason for wanting to be a validator on ropsten (something to test, represent a significant part of mainnet, significant experience running validators) and so on, then you would count as an entity :)

**Comment by VieYang** [comment]
Is there documentation on how to run Ropsten beacon chain?

**Comment by timbeiko** [comment]
@VieYang we'll have a post at blog.ethereum.org by the end of the week :-)

**Comment by 0xWildhare** [comment]
any tips on how to get 32 rETH? wen faucet?

**Comment by vacekj** [comment]
@0xWildhare if I don't have a validator setup before the merge, I can endow you with 32 rETH :shipit:

**Comment by nalepae** [comment]
> If there are entities outside of client teams that would like to take part, please comment below.

@parithosh We (https://www.kiln.fi/) would like to take part.

Besides running multiple validators on the mainnet, we run some validators on the Kiln testnet and would really like to have validators running during Ropsten merge.

**Comment by parithosh** [comment]
@nalepae Unfortunately the ropsten beaconchain genesis has already been created. So at this point to run multiple validators you'd need to make deposits manually. We'd make another such issue for Sepolia, perhaps you could comment there when its out?

**Comment by parithosh** [comment]
@nalepae sure, comment your address here :)

**Comment by nalepae** [comment]
@parithosh, here is my address:

`0x1268AD189526AC0b386faF06eFfC46779c340eE6`

==> Ideally we would like to launch 100 validators, so we would need 3200 rETH, if it is possible for you (we already have enough rETH for gas).

Thanks a lot!

**Comment by q9f** [comment]
https://whendoesropstenmerge.goerli.net/

**Comment by q9f** [comment]
Done. 🚀

**Comment by timbeiko** [comment]
Closing this as the beacon chain is alive and well!
