### ISSUE TITLE
Sepolia beacon chain

### ISSUE THREAD

**Issue by djrtwo** [ethereum/pm#526]
EDITED 

from @parithosh:

As discussed on ACD, Sepolia will have a minimal validator set. I'd say 100 validator keys per entity taking part (Assuming that every client team wants to take part) => Validator set of 1212 (9 client teams + EF + Attestant/Vouch + 12 for EF security + Alex).

Having a validator set of 100 per entity means that we can assign low number of keys (like 12) to entities such as EF security without them representing a significant portion of the network.

If there are entities outside of client teams that would like to take part, please comment below.

**Comment by q9f** [comment]
Did you discuss the option to have a small, permissioned validator set, i.e., something along the lines `MIN_GENESIS_ACTIVE_VALIDATOR_COUNT = 64` and a deposit contract that rejects new deposits afterward?

We should have one testnet that allows developers to expect a fairly stable application-test environment for dapp and contract developers (Sepolia?) whereas we have another one that can be used for consensus and execution client teams to test protocol mechanics (Goerli/Prater?). A small validator set would reduce the friction to maintain keys and validators long-term (IMO).

**Comment by parithosh** [comment]
Pro/Cons of various beaconchain sizes:

**Large beaconchain (2x mainnet):**
Pro:
- Easiest to bootstrap right at genesis
- We can use a token contract to save sepolia eth from being wasted
- Able to test a far higher load and be ahead of mainnet more easily

Cons:
- Client teams need to run a lot of validators on both prater and sepolia-beaconchain

**Small beaconchain**
Pro:
- Simpler to setup, easier on client teams
- Just one large network (prater) with all client teams running significant validators 

Cons:
- It would mean we'd need to continue making deposits on prater to catch up to mainnet => Spend a lot of goerli eth

**Comment by parithosh** [comment]
As discussed on ACD, Sepolia will have a minimal validator set. I'd say 100 validator keys per entity taking part (Assuming that every client team wants to take part) => Validator set of 1112 (9 client teams + EF + Attestant/Vouch + 12 for EF security). 

Having a validator set of 100 per entity means that we can assign low number of keys (like 12) to entities such as EF security without them representing a significant portion of the network. 

If there are entities outside of client teams that would like to take part, please comment below.

**Comment by q9f** [comment]
> If there are entities outside of client teams that would like to take part, please comment below.

I'd be happy to participate on behalf of the Goerli community.

**Comment by timbeiko** [comment]
On https://github.com/ethereum/pm/issues/528 we agreed that we should launch the sepolia beacon chain as soon as (reasonably) possible, and to confirm this with CL teams on the next CL call.

**Comment by lightclient** [comment]
Just wanted to leave a comment to say that I'm setting up a some infra to run a lot of validators on testnets (starting with prater) and would also be happy to also run on sepolia.

**Comment by nalepae** [comment]
> If there are entities outside of client teams that would like to take part, please comment below.

We would be happy to participate too.

**Comment by infosecual** [comment]
I just read the CL Call#88 notes and noticed that the sepolia beaconchain "will be permissioned, with ~2k validators." ([link](https://hackmd.io/@benjaminion/BkmzqV8uq))

Aside from the 12 validators that the EF CL Security Research team is slated to get we were planning to run other validators to test various things like slashing. We have been mining sepolia ETH for the last few days to seed this other set of validators. If the validator set will be permissioned I would like to request that we get more than 12 validators (maybe ~50) or that there is some method provided for us to deposit our mined SEP in a permissioned manner. 

The plan is to have 12 honest, longer term validators that are running various sanitizers (MSAN, ASAN, UBSAN, TSAN, etc.) and to have others that will either be slashed on purpose or otherwise not reliable in some fashion.

**Comment by q9f** [comment]
> The plan is to have 12 honest, longer term validators that are running various sanitizers (MSAN, ASAN, UBSAN, TSAN, etc.) and to have others that will either be slashed on purpose or otherwise not reliable in some fashion.

Please use Goerli/Prater for this.

**Comment by parithosh** [comment]
I think the idea is that they'd do this for each testnet, so they'd do this for goerli as well :)

**Comment by q9f** [comment]
What for?

**Comment by infosecual** [comment]
I think Goerli will suffice for this but I am not sure we can mine Goerli as it is POA.

**Comment by Emilijus436** [comment]
I would like to run 100 validators on Sepolia. I'm currently running a validator on Kiln and I previously ran a validator on Kintsugi, now I would also like to run some validators on Sepolia. I have over 200K Sepolia ETH.

**Comment by parithosh** [comment]
@Emilijus436 Do you represent a staking pool or have a specific reason you'd like to be a validator on sepolia? 

We'd ideally like to keep the sepolia validator set closed to known entities that currently stake significantly on mainnet (and have done a proven good job)

**Comment by Emilijus436** [comment]
@parithosh I started mining Sepolia on November 22, 2021 so that I can run a large amount of validators on Sepolia. For a long time, I was the only miner present on Sepolia. Getting 32 Goerli ETH is really hard right now.

**Comment by q9f** [comment]
> @parithosh I started mining Sepolia on November 22, 2021 so that I can run a large amount of validators on Sepolia. For a long time, I was the only miner present on Sepolia. Getting 32 Goerli ETH is really hard right now.

I can trade you Goerli Ether for Sepolia Ether 1:1. That might be the easiest for now? Send me a mail goerli at q9f dot cc or dm me on matrix @afr:tchncs.de (or join #goerli_chat:gitter.im). wdyt?

**Comment by ralexstokes** [comment]
@parithosh I'd take 100 validators to help with testnet stability and also client research. I believe I am the "Alex" in the top comment :)

**Comment by jacquesvcritien** [comment]
Simply Staking is part of the Ethereum Lido Node Operator set and we were wondering whether we could join the validator set to help in testing out the merge.

Thanks in advance and have a nice day!

**Comment by mcdee** [comment]
@parithosh for anyone signing up to run validators on this network, I think that we should be clear that this is a long-term commitment rather than an opportunity to test the merge.  As such, a confirmation that they are happy to run their validators in perpetuity would be a good idea.

**Comment by parithosh** [comment]
@mcdee Agreed, All of the people who are in the validator set reached out personally as well and I've clarified the requirements with them. 

The expectation is that the validators need to be run in perpetuity or handed over/exited when circumstances change.

**Comment by nalepae** [comment]
We are currently struggling to find our SepoliaETH to run our 100 Sepolia validators.
Anybody who can help us with that? @parithosh ?

Have a nice day!

**Comment by parithosh** [comment]
@nalepae You don't have to acquire any sepolia eth for the validators. I'll be creating the genesis state with your deposits baked in. Can you DM/Email me to discuss it?

**Comment by nalepae** [comment]
Sure!

**Comment by Sepolia-Testnet** [comment]
We would like to runn 100 validators for sepolia.dev to use in funding out faucet

**Comment by parithosh** [comment]
We've unfortunately already generated the genesis config. But I'll be happy to redirect the fee_recipient address of the EF nodes to a faucet/group of faucets :)

**Comment by parithosh** [comment]
The genesis configs for sepolia can be found here: https://github.com/eth-clients/merge-testnets/tree/main/sepolia

The validator keys have been sent to all parties that requested it, in case you haven't heard from me - please do ping me ASAP.

**Comment by eth2devops** [comment]
@parithosh I am willing to be a sepolia genesis validator as I represent Obol core devs team. In [Obol Network](https://obol.tech/) we run different validators with different testnets to develop and test our DV technology ([charon](https://github.com/ObolNetwork/charon). We are willing to do the same with sepolia and we are ok to run validators for the long-term.

**Comment by moshe-blox** [comment]
I know it may be too late, but even though I was anticipating Sepolia, I only just noticed this discussion :-\

We've been mining Sepolia ETH for a few months already at [SSV Network](https://ssv.network).

@parithosh Is there a chance for a last day genesis inclusion?
If not, what about a post-genesis inclusion?

Regardless, we have a surplus of a few 1000's Sepolia ETH, if anyone needs 😉

**Comment by parithosh** [comment]
@moshe-blox Unfortunately its too late to change the genesis state. But we can onboard you post genesis and pre-merge. I'll create a guide and reach out to all the interested parties soon. What's the best way to reach you?

**Comment by moshe-blox** [comment]
@parithosh Thanks, that's great to hear :-)

At first, we're gonna run the Sepolia validators under [Blox Staking](https://bloxstaking.com) to properly prepare it for The Merge. (since it already operates ~2k validators on mainnet)

*(Blox Staking runs a custom validator client with a [non-custodial signing mechanism](https://github.com/bloxapp/key-vault) over Prysm & Lighthouse Beacon nodes.)*

Later, we might migrate them to SSV Network for internal testing, and then just migrate them back under Blox Staking forever (or, in coordination with you, exit / hand them over to someone else who needs.)

Best way to contact me is via **moshe@blox.io** or via `moshe [BloxStaking.com]#3344` (Discord)

**Comment by aertoria** [comment]
Hi @parithosh 
My engineering team is working on supporting Sepolia testnet. We are going to use Geth for execution layer, now Sepolia validator is permissioned, what's our option on consensus layer? Can Sepolia only run on EL without CL?

**Comment by q9f** [comment]
@aertoria You can run a CL without a validator and only follow the beacon chain. Any client will work.

I personally run a Geth + Lodestar tuple on Sepolia.
