### ISSUE TITLE
EIP-4844 Breakout Room 

### ISSUE THREAD

**Issue by timbeiko** [ethereum/pm#543]
### Meeting Info
* [June 17, 2022, 14:00 UTC](https://savvytime.com/converter/utc-to-germany-berlin-united-kingdom-london-ny-new-york-city-ca-san-francisco-china-shanghai-japan-tokyo-australia-sydney/jun-17-2022/2pm)
* Duration: 60 minutes
* Youtube Recording: https://youtu.be/flx1hDUV8O0
* Zoom: shared on #sharded-data Discord server shortly before the call 

### Agenda

1. Implementation updates 
2. KZG Ceremony updates 
   - https://github.com/ethereum/kzg-ceremony-specs
3. 4844 Open Issues/R&D questions/Tooling Requirements
    - Blob Verification 
    - Fee Market 
    - Blob Sync 
5. Next steps 
    - EthCC/EthBerlin

**Comment by timbeiko** [comment]
Notes from the call: https://docs.google.com/document/d/1KgKZnb5P07rdLBb_nRCaXhzG_4PBoZXtFQNzKO2mrvc/edit#heading=h.c0273egri56a

**Comment by poojaranjan** [comment]
Recording: https://youtu.be/flx1hDUV8O0
