### ISSUE TITLE
wss://nunki.htznr.fault.dev/ws Connection error

### ISSUE THREAD

**Issue by ganyuanmen** [ethereum/pm#573]
Created a public endpoint for sepolia if anyone needs.
* HTTPS: `https://nunki.htznr.fault.dev/rpc`
* WSS: `wss://nunki.htznr.fault.dev/ws`

See also
* https://github.com/goerli/sepolia

_Originally posted by @q9f in https://github.com/ethereum/pm/issues/460#issuecomment-1116183241_

I use the following code:
web3 = await new Web3(" wss://nunki.htznr.fault.dev/ws ");
console. log(web3)
Used to listen to contract events and return an error:
connection not open on send()

**Comment by q9f** [comment]
the endpoint was abused and I had to shut it down, unfortunately.
