### ISSUE TITLE
Ethereum Core Devs Meeting Constantinople Session 2 Agenda

### ISSUE THREAD

**Issue by Souptacular** [ethereum/pm#61]
# Ethereum Core Devs Meeting Constantinople Session 2 Agenda
### [Constantinople Progress](https://github.com/ethereum/pm/issues/53)

# Agenda
1. Ropsten issues.
2. When fork?

**Comment by lows93** [comment]
will we go back to the future ?

`Meeting Date/Time: Friday 31 August 2018 at 14:00 UTC´

**Comment by lrettig** [comment]
Fixed the date

**Comment by Souptacular** [comment]
lol @lrettig we fixed it at literally the exact same minute and GitHub errored out for me.

**Comment by lrettig** [comment]
Good to know consensus by GitHub works so well 👍

**Comment by lrettig** [comment]
This is my attempt to summarize the things that went wrong - and by extension, things I'd love to discuss on Friday's call. Please make additions/corrections! https://ethereum-magicians.org/t/issues-we-discovered-in-the-ropsten-constantinople-hard-fork/1598

**Comment by 5chdn** [comment]
I approve this thread, Lane, and I appreciate that you collected all these items. There are two differences though:

1. I tried to order my items in a chronological manner.
2. I tried to focus on all the things that are immediately important for the call.

But it totally makes sense to also go through the additional questions you raised, but maybe not all in one call :rofl:

**Comment by AlexeyAkhunov** [comment]
I will not be able to join the call. I have read @lrettig thread on Magicians. What is missing there and also here: we need to answer the question: "What is the plan between now and mainnet hard-fork?". Clearly, we are not rolling back Ropsten, and keep testing things there. So I propose regularly spawning (and mining) temporary test nets to test transition to Constantinople with any clients that want to participate. It is important to test both the new code (on Ropsten now), and the tools and processes used for transition (not possible on Ropsten anymore).

**Comment by AlexeyAkhunov** [comment]
Oh, and also forgot another suggestion - what about bounties for causing consensus issues on Ropsten?

**Comment by egalano** [comment]
I'd like to propose bounties for running nodes or mining on Ropsten as well to encourage more community participation. At the very least during the periods leading up to a fork.

**Comment by 5chdn** [comment]
> we need to answer the question: "What is the plan between now and mainnet hard-fork?"

Tests! :)

**Comment by eggy-eth** [comment]
How about someone also writes down the main points which are discussed in the call? I would really like to know, for example, what the consensus is on the second point. I know I can also listen to the call again, but this means I have to spend a hour to listening to the video to farm out all the points which have to be raised. I really think it would help more people as well to quickly get a "tldr" of the call.

**Comment by lows93** [comment]
So tldw; 
- Mainnet Hardfork not before January / End of January
- time between release Hardfork-Client  and the Hardfork itself should be atleast 4 Weeks
- possible Progw for the upcoming Hardfork
- for Istanbul and further Hardforks there should be a Testphase on Testnet for min. half a year

**Comment by lrettig** [comment]
Notes are up: https://github.com/ethereum/pm/blob/master/All%20Core%20Devs%20Meetings/Constantinople%20Meeting%202.md

**Comment by olalawal** [comment]
If progpow is a definate go for implementation in the delayed for Me and my conglomerate of freelance miners are happy to set up a pool on Testnet and provide testing.  We currently run a BCI progpow pools and Yiimp as well.

our discord:
https://discord.gg/7VRe2aW
