### ISSUE TITLE
EIP-3675 Status

### ISSUE THREAD

**Issue by solomontan88** [ethereum/pm#617]
Why is EIP-3675 is status is still last call, despite last call deadline is August 31, 2022, and now it is September 7, 2022 ?

**Comment by solomontan88** [comment]
https://eips.ethereum.org/EIPS/eip-3675

**Comment by solomontan88** [comment]
@timbeiko @vbuterin @mkalinin @djrtwo

**Comment by mkalinin** [comment]
It will be moved to Final after transition on the Mainnet
