### ISSUE TITLE
Consensus-layer Call 95

### ISSUE THREAD

**Issue by solomontan88** [ethereum/pm#618]
# Consensus-layer Call 95 Agenda
[prev: call 94](https://github.com/ethereum/pm/issues/598)

Meeting Date/Time: Thursday 2022/9/8 at 14:00 UTC
Meeting Duration 1.5 hours 
[livestream](https://www.youtube.com/watch?v=ir-gnBm2GZ4)

1. Merge
    * opti-sync tests https://github.com/ethereum/consensus-specs/pull/2982
6. Research, spec, etc
    * checkpoint sync api https://github.com/ethereum/beacon-APIs/pull/226
8. Open Discussion/Closing Remarks

**Comment by djrtwo** [comment]
Thanks @solomontan88 for posting

**Comment by mkalinin** [comment]
I'd like to get the general feeling about https://github.com/ethereum/beacon-APIs/pull/226

**Comment by solomontan88** [comment]
Where is livestream link ? @djrtwo

**Comment by solomontan88** [comment]
> I'd like to get the general feeling about [ethereum/beacon-APIs#226](https://github.com/ethereum/beacon-APIs/pull/226)

Good idea...

**Comment by solomontan88** [comment]
Alert @djrtwo @mkalinin @timbeiko @vbuterin 
Why is livestream called Consensus Layer Call #99 ?, I think that's wrong... It's Consensus Layer Call #95 NOT #99
https://www.youtube.com/watch?v=ir-gnBm2GZ4
![image](https://user-images.githubusercontent.com/112005550/189131588-424197b9-14a3-4ca3-af4a-6c8f1d10ef17.png)

**Comment by timbeiko** [comment]
Last minute addition to the agenda, if time permit - I'd like to get team's feedback on the idea of cancelling some CL/ACD calls after the merge for a bit of breathing space and potentially having discussions related to Shanghai EIPs async over those weeks.

**Comment by solomontan88** [comment]
> Last minute addition to the agenda, if time permit - I'd like to get team's feedback on the idea of cancelling some CL/ACD calls after the merge for a bit of breathing space and potentially having discussions related to Shanghai EIPs async over those weeks.

Is there any time estimation for Shanghai EIPs implementation ?
