### ISSUE TITLE
After completed initial stage of syncing goes to stale process 

### ISSUE THREAD

**Issue by lokeshratnam09** [ethereum/pm#625]
After ethereum network merging my beacon node already get synced but my geth client complete the initial stage syncing process and swich to stale process but I don't know how much time geth client will take the full node sync it's almost completed 2 days but geth client is not synced.
Please help l am in very big problem.

**Comment by holgerd77** [comment]
This is the wrong repository to ask questions like this since this is an (eventual) client specific software issue you are describing. Please ask in the Go-Ethereum repository or chat or (maybe better) on the side of the respective beacon/consensus client you are using.
