### ISSUE TITLE
Proposal to add EIP-2294 to Shanghai 

### ISSUE THREAD

**Issue by xinbenlv** [ethereum/pm#645]
I like to add [EIP-2294](https://eips.ethereum.org/EIPS/eip-2294) to shanghai, which specifies chainId size and bound

**Comment by timbeiko** [comment]
We finalized the scope for Shanghai on ACD151, and discussions about Cancun inclusion should be moved to https://ethereum-magicians.org/t/cancun-eip-consideration/12060
