### ISSUE TITLE
EOF Devnets Breakout Room 

### ISSUE THREAD

**Issue by timbeiko** [ethereum/pm#653]
## Meeting Info
- [Nov 4, 2022, 14:00 UTC](https://savvytime.com/converter/utc-to-germany-berlin-united-kingdom-london-ny-new-york-city-ca-san-francisco-china-shanghai-japan-tokyo-australia-sydney/nov-4-2022/14-00)
- Duration: 60 minutes
- Recording: https://youtu.be/3Nx0z0-bhsU 
- Notes: https://notes.ethereum.org/@timbeiko/eof-breakout

📆  Subscribe to the [Ethereum Protocol Call calendar](https://calendar.google.com/calendar/u/1?cid=Y191cGFvZm9uZzhtZ3JtcmtlZ243aWM3aGs1c0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t) for calendar invites

## Agenda
- EOF "feature complete" EIPs list 
    - EIP-3540
    - EIP-3670
    - EIP-4200
    - EIP-4750
    - Anything else?
- EOF devnet 1 
    -  Target EIPs
    -  Client Implementations
    - Testing

**Comment by bobsummerwill** [comment]
Great, thanks, @timbeiko!

CC @diega, @meowsbits, @ziogaschr.

**Comment by bobsummerwill** [comment]
EOF OneShot™ specifications:

* EIP-3540 - [EVM Object Format (EOF) v1](https://eips.ethereum.org/EIPS/eip-3540)
* EIP-3670 - [EOF - Code Validation](https://eips.ethereum.org/EIPS/eip-3670)
* EIP-4200 - [Static relative jumps](https://eips.ethereum.org/EIPS/eip-4200)
* EIP-4750 - [EOF - Functions](https://eips.ethereum.org/EIPS/eip-4750)

Unnecessary if the above are activated?
* EIP-3690 - [EOF - JUMPDEST Table](https://eips.ethereum.org/EIPS/eip-3690)

Earlier attempts at EVM versioning, static jumps and subroutines:
* EIP-615 - [Subroutines and Static Jumps for the EVM](https://eips.ethereum.org/EIPS/eip-615)
* EIP-1702 - [Generalized Account Versioning Scheme](https://eips.ethereum.org/EIPS/eip-1702)
* EIP-2315 - [Simple Subroutines for the EVM](https://eips.ethereum.org/EIPS/eip-2315)

**Comment by bobsummerwill** [comment]
Suggested formatting tweak for 4200 and 3540 titles:
https://github.com/ethereum/EIPs/pull/5849

**Comment by axic** [comment]
The last piece is [EIP-540: EOF - Stack Validation](https://eips.ethereum.org/EIPS/eip-5450) removes the need for stack underflow checks and most cases of overflow checks.

**Comment by bobsummerwill** [comment]
Thanks.  Updated in https://github.com/ethereum/pm/issues/653#issuecomment-1295347461, @axic.

**Comment by chfast** [comment]
I'd do the **first** iteration with the ones already implemented for Shanghai:
* EIP-3540 - [EVM Object Format (EOF) v1](https://eips.ethereum.org/EIPS/eip-3540)
* EIP-3670 - [EOF - Code Validation](https://eips.ethereum.org/EIPS/eip-3670)

and also include:
* EIP-3855 - [PUSH0 instruction](https://eips.ethereum.org/EIPS/eip-3855) (EVM related and very easy to add)
* EIP-3860 - [Limit and meter initcode](https://eips.ethereum.org/EIPS/eip-3860) (Important because this covers the EOF validation cost)

This should stabilize what has been already implemented (including state tests).

In the **second** stage we should include:
* EIP-4200 - [Static relative jumps](https://eips.ethereum.org/EIPS/eip-4200)
* EIP-4750 - [EOF - Functions](https://eips.ethereum.org/EIPS/eip-4750)

For **later** we have:
* EIP-5450 - [EOF - Stack Validation](https://eips.ethereum.org/EIPS/eip-5450)
* and some other ideas (just some examples, let's keep the discussion for some other place and time):
   * unlimited `DUP` and `SWAP`
   * instruction cleanups (e.g. get rid of output arguments for calls)
   * gas observability
   * `NOP` instruction
   * [gas cost reduction](https://github.com/imapp-pl/gas-cost-estimator/blob/master/docs/gas-cost-estimator.md#appendix-b-evm-opcodes-and-their-gas-cost-estimates)

**Comment by gcolvin** [comment]
The trouble with doing things in stages is that it would take years.  Until Stack Validation is in we will not have even have the functional equivalent of EIP-615, which is the least we need to allow us to compile EVM code to machine code in linear time and space.

**Comment by shemnon** [comment]
The concern I have with stack validation is there is basically no specification in the EIP as to what "the instruction flow traversal procedure, where every possible code path is examined, and data stack height at each instruction is recorded" is apart from the reference implementation in python.  And then that reference implementation I read as O(n^2), not good for critical path code and a target for attacks.

For comparison the JVM has an entire section on code validation (https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.10), but they are adding in type validation at each stack entry. section [4.10.2.2](https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.10.2.2) is more about what I expect the specification would be.

**Comment by gcolvin** [comment]
The algorithm can be and should be linear in time and space.  (The Wasm algorithm is.)   If it's not it needs fixing.

EIP-615 provided essentiality the same safety guarantees as the full EOF suite,  stated as both a set of constraints on valid code and an algorithm to validate those constraints.   EIP-2315 also takes this approach for a weaker set of guarantees.  So validity can be stated as a set of constraints independently of the algorithm that enforces those constraints.

(Again, the Wasm spec is entirely declarative.  The validation algorithm is a non-normative appendix.)

EIP-5450 enforces essentiality the same constraints as EIP-615, but you have to go through all of the EIPs it requires to find them and their corresponding validation algorithms.  Most of the constraints are expressed as exceptional halting conditions on instruction execution which validation seeks to prevent.  It might be helpful to restate all of the constraints in EIP-5450 and to give a single, unified validation algorithm.

And yeah, we only have one data type, so only the number of items on the stack matters.  If that ever changes we will need to expand our EOF tables to include JVM-style stack maps and expand the validation algorithm accordingly.

**Comment by gcolvin** [comment]
And a minor "marketing" suggestion:
> ***EVM2*** = EOF(eip-3540, eip-3670, eip-4200, eip-4750, eip-5450)

**Comment by shemnon** [comment]
EOF version 1 is EVM 2?  Not as bad as ProgEVM, but not great.  There's also confusion with the EVMOne project, would EVMTwo be the successor?

If it needs differentiation (and I'm not sure that would help marketing wise) I would want something like EEVM for "Encapsulated EVM".

**Comment by gcolvin** [comment]
For me, the most important thing is that what the Ipsilon team is proposing is a Validated EVM.  Good things will come of that.

**Comment by bobsummerwill** [comment]
@AlexeyAkhunov Is anybody from Erigon planning to attend?  Best wishes!

**Comment by holgerd77** [comment]
Just reading up on the call notes here, so we are working on withdrawals right now and will be ready with this in 1-2 weeks, if wished we can happily reboot the Shandong testnet in a v2 version without the EOF stuff and then additionally including withdrawals.

**Comment by gumb0** [comment]
> The concern I have with stack validation is there is basically no specification in the EIP as to what "the instruction flow traversal procedure, where every possible code path is examined, and data stack height at each instruction is recorded" is apart from the reference implementation in python. And then that reference implementation I read as O(n^2), not good for critical path code and a target for attacks.
> 
> For comparison the JVM has an entire section on code validation (https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.10), but they are adding in type validation at each stack entry. section [4.10.2.2](https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.10.2.2) is more about what I expect the specification would be.

We don't claim python reference implementation is the most efficient, but it is linear in number of instructions, as each instruction is examined once and python dict lookup (which is O(1)) is done for each one. It's basically CFG traversal in breadth-first-search manner (where the only branches are RJUMPI).

Thank you for the pointer to Java validation spec, it will help us to try to better describe the algorithm verbally.
