### ISSUE TITLE
The Progress Tracker should say trinity has not implemented Net Gas Metering

### ISSUE THREAD

**Issue by lithp** [ethereum/pm#68]
https://github.com/ethereum/py-evm/pull/1410 has been merged but https://github.com/ethereum/py-evm/issues/1105 is still open, because the Constantinople tests aren't passing yet.

Opening this ticket because I'm not sure whether I should go in and change [this page](https://github.com/ethereum/pm/wiki/Constantinople-Progress-Tracker) myself, maybe there's a process for changes there that I would be bypassing?

**Comment by lrettig** [comment]
It's a wiki which anyone can edit so you should feel free to edit it. CC @pipermerriam, @carver
