### ISSUE TITLE
EOF Breakout Room #4

### ISSUE THREAD

**Issue by lightclient** [ethereum/pm#690]
## Meeting Info
* [Dec 15, 2022, 16:00 UTC](https://savvytime.com/converter/utc-to-germany-berlin-united-kingdom-london-ny-new-york-city-ca-san-francisco-china-shanghai-japan-tokyo-australia-sydney/dec-2-2022/16-00)
* Duration: 60 minutes
* Zoom: https://ethereumfoundation.zoom.us/j/86404432301?pwd=ZC9Id1FXNUZFNnFBaUpoRk5tdXBKUT09

📅 Subscribe to the [Ethereum Protocol Call calendar](https://calendar.google.com/calendar/u/1?cid=Y191cGFvZm9uZzhtZ3JtcmtlZ243aWM3aGs1c0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t) for calendar invites

### Agenda
* Client updates
* Compiler updates
* Spec updates
* Open Issues
  * header format
  * stack cleanup on `RETF` and `JUMPF`
  * disallowing unreachable code?
  * [EOF spec level open issues](https://notes.ethereum.org/@ipsilon/eof1-checklist#Spec-level-Open-Issues)
* Shanghai Timeline 
* (time permitting): [banning code introspection](https://ethereum-magicians.org/t/eof-proposal-ban-code-introspection-of-eof-accounts/12113/12)

**Comment by moodysalem** [comment]
Could [banning code introspection](https://ethereum-magicians.org/t/eof-proposal-ban-code-introspection-of-eof-accounts/12113/12) be added to the agenda? It seems necessary to avoid accumulating EOF versions over time in perpetuity (at least until the future EOF version where it is solved)

**Comment by lightclient** [comment]
If we have time we should discuss, but currently the main priority is finalizing the last few pieces of the Shanghai EOF spec.

**Comment by poojaranjan** [comment]
Breakout Room 4 [Notes](https://hackmd.io/@poojaranjan/EOFBreakOutNotes#EOF-Breakout-Meeting-4)

**Comment by lightclient** [comment]
closing in favor of #692

**Comment by poojaranjan** [comment]
Recording: https://youtu.be/bOID9rklh4U
