### ISSUE TITLE
Where do you request an EIP to be CFI for cancun?

### ISSUE THREAD

**Issue by Pandapip1** [ethereum/pm#713]
The current list:

* Adding `cancun-candidate` tag on Ethereum Magicians
* Posting to the [Cancun EIP Consideration](https://ethereum-magicians.org/t/cancun-eip-consideration/12060/5) thread on Ethereum Magicians
* Submit a PR to `ethereum/execution-specs` or `ethereum/consensus-specs` (depending on content of EIP) adding the EIP to the CFI list & implementation table
* Create a GitHub issue on `ethereum/pm`

Which of these is the best option?

**Comment by ralexstokes** [comment]
I think following the spirit of @timbeiko 's post here: https://ethereum-magicians.org/t/proposal-network-upgrade-meta-threads/12552

> Posting to the [Cancun EIP Consideration](https://ethereum-magicians.org/t/cancun-eip-consideration/12060/5) thread on Ethereum Magicians

is the best for now

cancun is likely some months away and it feels to _me_ like we are still very early in the Cancun planning process; i.e. pre-consensus so we can all just get partial views of each other's "mempools" -- where the magician's EIP consideration thread seems like a good place to collate attention for now

**Comment by timbeiko** [comment]
+1 to all that. I'd like us to have a proper discussion around the process itself before we start filling the upgrade with EIPs :-)

**Comment by timbeiko** [comment]
We agreed to the meta threads on ACD153, closing this
