### ISSUE TITLE
SSZ Transactions Breakout Room 

### ISSUE THREAD

**Issue by timbeiko** [ethereum/pm#721]
## Meeting Info
- [Feb 15, 2023, 15:00 UTC](https://savvytime.com/converter/utc-to-germany-berlin-united-kingdom-london-ny-new-york-city-ca-san-francisco-china-shanghai-japan-tokyo-australia-sydney/feb-15-2023/15-00)
- Duration: 60 minutes
- Recording: https://youtu.be/T5aMpivk-Gw 

📆  Subscribe to the [Ethereum Protocol Call calendar](https://calendar.google.com/calendar/u/1?cid=Y191cGFvZm9uZzhtZ3JtcmtlZ243aWM3aGs1c0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t) for calendar invites

## Agenda 

* Discussion of various SSZ proposals & their impact on EIP-4844
    * [Potential Transaction SSZ Refactor](https://notes.ethereum.org/@vbuterin/transaction_ssz_refactoring)
    * [EIP-6404](https://github.com/ethereum/EIPs/pull/6404)

**Comment by etan-status** [comment]
There is also interest in changing transaction signatures and perpetual ID to be SSZ based: https://github.com/ethereum/EIPs/pull/6385

**Comment by etan-status** [comment]
[SSZTX.pdf](https://github.com/ethereum/pm/files/10726564/SSZTX.pdf)

Supporting graphics for the `Union/Onion` vs `Normalized Transaction` merkle trees.
Left out the 0-blob 4844 BasicTransaction for now, it doesn't matter for this context.

**Comment by timbeiko** [comment]
Closed in favour of https://github.com/ethereum/pm/issues/new
