### ISSUE TITLE
SSZ Transactions Breakout Room #2

### ISSUE THREAD

**Issue by timbeiko** [ethereum/pm#727]
## Meeting Info
- [Mar 1, 2023, 15:00 UTC](https://savvytime.com/converter/utc-to-germany-berlin-united-kingdom-london-ny-new-york-city-ca-san-francisco-china-shanghai-japan-tokyo-australia-sydney/mar-1-2023/15-00)
- Duration: 60 minutes
- Recording: https://youtu.be/Nl7iwAcqekY

📆  Subscribe to the [Ethereum Protocol Call calendar](https://calendar.google.com/calendar/u/1?cid=Y191cGFvZm9uZzhtZ3JtcmtlZ243aWM3aGs1c0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t) for calendar invites

- Previous Call Recording: https://youtu.be/T5aMpivk-Gw 

## Agenda 
- Performance of Union vs. Normalized format across various use cases
- Next steps for EIP-4844/Dencun

**Comment by etan-status** [comment]
- Union vs Normalized: https://eips.ethereum.org/EIPS/eip-6404 (ongoing updates)
- SSZ Signature scheme: https://ethereum-magicians.org/t/eip-6493-ssz-transaction-signature-scheme/13050

**Comment by hanabi62513** [comment]
俺のメール送ってくるな

2023年2月25日(土) 10:44 Etan Kissling ***@***.***>:

**Comment by timbeiko** [comment]
Recording here: https://youtu.be/Nl7iwAcqekY
