### ISSUE TITLE
Execution Layer P2P Breakout #1

### ISSUE THREAD

**Issue by timbeiko** [ethereum/pm#810]
## Meeting Info
- [July 12, 2023, 15:30 UTC](https://savvytime.com/converter/utc-to-germany-berlin-united-kingdom-london-ny-new-york-city-ca-san-francisco-china-shanghai-japan-tokyo-australia-sydney/jul-12-2023/13-00)
- Duration: 60 minutes
- Recording: TBA 
- Zoom: https://ethereumfoundation.zoom.us/j/85035470076?pwd=RFhTTnp6U29UVXpxbW1ZOXp6YTZmUT09

📆  Subscribe to the [Ethereum Protocol Call calendar](https://calendar.google.com/calendar/u/1?cid=Y191cGFvZm9uZzhtZ3JtcmtlZ243aWM3aGs1c0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t) for calendar invites

## Agenda
- EL networking spec proposals 
    - Transaction pool considerations

**Comment by fjl** [comment]
For next call agenda:

- discv5 support in nethermind, interop test planning
- adding available block range into eth protocol handshake
