### ISSUE TITLE
Holesky Testnet Launch Coordination Call #1

### ISSUE THREAD

**Issue by parithosh** [ethereum/pm#814]
To replace Goerli by end of this year, we proposed to launch [Holesky](https://github.com/eth-clients/holesky) to launch not later than September.

This breakout call is to discuss the timeline, validator set and discuss any other related topics. 
  - Thursday, June 29, 2023, 12:30 UTC

Agenda
    - Get updates from client teams and validator commitments
    - Discuss alternate ways to achieve a stable validator set
    - Discuss strategies for initial genesis allocation (or mass seeding of developer/staker accounts)
    - Discuss upper limit of native eth clients can handle, is it uint64 or higher? We can inflate the supply near the limits

We would like to invite representatives of the client teams to discuss and other testnet enthusiasts, e.g. ethstaker, ephemery. Feel free to add more items to the agenda if necessary.

Some notes from the last call can be found here:
- https://notes.ethereum.org/@parithosh/holesky-planning
- https://github.com/ethereum/pm/issues/803#issuecomment-1593108937

Zoom: shared on #allcoredevs Discord channel shortly before the call

**Comment by mcdee** [comment]
Regarding "strategies for initial genesis", I haven't seen numbers for either consensus or execution layer as to the impact of having a large initial state.  Anyone from the teams able to share some insight on this?

**Comment by philknows** [comment]
For this call @parithosh, @q9f will not be available and will not be posting a meeting link. I can gladly host or just join in on an EF link you provide here.

**Comment by parithosh** [comment]
It'd be great if you could host it in that case @philknows , I've just a free tier zoom account and don't want us getting kicked out(We usually use jitsi, but I'm not sure how many people will show up and if it would crash due to the load)

**Comment by philknows** [comment]
Call begins in about ~1hr here:
https://chainsafe-io.zoom.us/j/81069694201?pwd=UkdIL2wxL3VSZ1YzOWxZUGVBTERWUT09

**Comment by philknows** [comment]
Current commitments from teams and community is at 1.746m @parithosh 
https://hackmd.io/sz5x-s3AQVmPJQW7j7AfEA

**Comment by darrenlangley** [comment]
For the consensus genesis validators, will they use 0x0 or 0x01 withdrawal credentials? 

I guess for most 0x01 is convenient. In Rocket Pool's case, it would be great to either have 0x0 or a mix so that we can use them to bootstrap our official testnet on Holesky (via our 0x0 migration process).

It isn't a big deal for us we can manage either way but thought I would ask.

**Comment by mcdee** [comment]
@darrenlangley we should have a mix, but mainly 0x00 at genesis so that we can generate a number of BLS to execution change operations on-chain, to mirror the fact that we have a number of them on mainnet.

**Comment by parithosh** [comment]
Key Takeaways:
- We reached out required commitment of 1.5M validators, we're currently at 1.7M and would like to close the signups
- The client teams are currently making up ~800k
- Genesis ETH allocation size of ~few 100M ETH. That way we have enough ETH for faucets/validators but don't have to worry about supply overshoot issues.
- We stick to mainnet values as it allows for predictable testing.
- We set the allocations similar to https://github.com/eth-clients/holesky/issues/1 but modifying the values to sane numbers.The post genesis seeding can happen via scripts.

Rough timeline:
- End July: Complete testing to ensure CLs can handle the validator state size
- End July: Create genesis state and start review
- 7th Aug: End of review period, clients can start releases with state
- Mid Aug: Releases from all clients with `--holesky` flag
- Mid Sept: Chain genesis

Note: Updates shared on ACDC/ACDE unless there are more discussion points needing a breakout call. If not, we can have another breakout call closer to the genesis file release date.
