### ISSUE TITLE
Argument against auto compounding for staking fee (for Consensus-layer Call 113)

### ISSUE THREAD

**Issue by fulldecent** [ethereum/pm#822]
I see this issue wasn't created yet, but I have an agenda item to add to meeting 113.

---

# Argument against auto compounding for staking fee

William Entriken

2023-07-04

Changing the fee to auto-compounding makes Ethereum appear as an interest-bearing security. We must end all consideration of this change.

## A brief history of time

Some time in 2021 regulators in the United States, Europe and other regimes have basically come to accept Bitcoin and Ethereum as commodities/currency. This is a preferable to being considered a security. Hopefully this point does not require elaboration. Many other projects are considered as securities, from a now-famous comment by the U.S. Securities and Exchange Commission chair. Even other projects that are basically the same as Ethereum are considered securities, but Ethereum has been effectively exempted because "it's been around for a while", and "it's running on its own."

Then Ethereum released version 2.0 which makes Ether payments are given for participating in staking/validating.

Regulators have not said very much about this change. And they have not explicitly made a technical analysis of this mechanism. But generally the atmosphere is that "Ethereum is the same thing" and so there has not been a reevaluation.

Now Ethereum is preparing version 3.0 which changes Ether payouts to be auto-compounding. Yes, changing the way you pay out Ether is a MAJOR release version, every time. According to SemVer.

## These are major changes

**Every time we change payouts, fees, minting/burning, there is a possibility that regulators will reevaluate Ethereum and decide that it no longer qualifies as a commodity and that it instead is a security, or a money laundering platform or whatever else they want to classify it as.**

**Additionally, because Ethereum is a centralized application where you, the core devs, decide what is in the next version, and everybody else has to upgrade, the things you discuss (i.e. this meeting) are all part of the discoverable testimony that can be considered as part of regulators' decisions. Eventually regulators will realize they can just compel you to ban Tornado Cash (U.S. Treasury) or require back doors in everything (EU Data Act), but that's a blog post for a different day.**

But back to compounding interest...

# This major change

If a validator receives payment for validating, this is and appears to be payment-for-services. Normal people understand that. Regulators understand that.

If a validator receives a second payment for validating a second thing... same thing... that appears to be payment-for-services.

Let's rewrite that with compounding.

The first time a validator receives payment for validating. Payment-for-services.

Then the second time the validator receives payment for validating... and ALSO extra payment for the money that they put into the system (i.e. the payout from the first services). What's that? It's interest. Normal people would call that interest. And regulators would call it that too.

## Summary

In summary, a change to Ethereum staking payouts which introduces compounding payments is being considered. Normal people and regulators will see this as interest. Payout of interest might result in Ethereum being classified as a security by any of the myriad regulators on Earth. We must end any discussion of this.

Instead we must only consider validators as active, witting participants in the network security, whereas those people are performing effort to run validator nodes and Ethereum is paying them for their efforts in running a secure node. Running a secure node is difficult, trying new clients is difficult, and THIS is why payment is made to those participants. Payment is never based on, predicated on, or motivated by any investment in a common enterprise nor an incentive for moving money in (or not moving money out of) an account.

**Comment by djrtwo** [comment]
Please take this to an appropriate forum such as the ethereum magicians forum -- https://ethereum-magicians.org

The proposal you are referring to is an active research and design proposal and is not currently being considered for inclusion much less even clear where the research direction might go from there. Any status update and/or discussion on this proposal is theoretical and being evaluated on technical merits only at this time.

Given this *research and design* proposal's infancy, we will not be taking time to discuss it's non-technical implications on ACD anytime soon, and given there are many R&D paths and potential futures, won't be spending too much time on this one proposal in general in the context of the pressing discussions around the next couple of forks.

I suggest discussing on eth magicians, writing blog posts about your concerns, and using other means to extend your arguments and build consensus outside of this call, if this is an important point to the larger ethereum community.

**Comment by fulldecent** [comment]
My understanding is that this discussion topic was originally raised in the PM phone call.

If so then then then it IS appropriate for my note to be added to the next PM call.

Nothing in life is a technical-only discussion. And it is inappropriate to censor discussion on such grounds. 

---

If this topic has already originated on some other forum before it came to PM then I would appreciate a link to that specific thread and I will paste my note there.

**Comment by djrtwo** [comment]
Technical proposals are discussed on ACD regularly. This is a technical proposal in it's infancy and has been brought to get technical feedback. It is in no way being discussed for inclusion but rather is in a technical exploration to better understand technical design trade-offs.

This technical post has discussion on the Eth R&D discord and ethresear.ch forum. You're arguments are not about technical merits but instead about a notion that governance should take into consideration specific legal jurisdictions. The best place to discuss governance especially in relation to an R&D direction that is in its infancy is likely the eth magicians forum and/or blog posts.

**Comment by fulldecent** [comment]
I do not see any discussion of auto compounding interest on ETHResear.ch or on ethereum-magicians.org.

As far as I can tell, the seminal discussion occurred on this PM call.

Therefore appropriate place to read my note into the record is the next PM call.

---

The PM call is a business meeting including people that have authority to design the next Ethereum version. (Remember... we don't "vote" for upgrades in Ethereum land.)

In Europe laws are already drafted which define liability for people making these kinds of decisions (see Data Act, 2023).

So it is definitely in the interest of present people to consider this liability.

**Comment by zhongfu** [comment]
> I do not see any discussion of auto compounding interest on ETHResear.ch or on ethereum-magicians.org.

you're probably looking for [this topic](https://ethresear.ch/t/increase-the-max-effective-balance-a-modest-proposal/15801) about increasing the MaxEB, which would be required to allow for auto-compounding

**Comment by fulldecent** [comment]
Thank you for the reference. I posted these notes there to https://ethresear.ch/t/increase-the-max-effective-balance-a-modest-proposal/15801/48?u=fulldecent
