### ISSUE TITLE
Execution Layer P2P Breakout #2

### ISSUE THREAD

**Issue by smartprogrammer93** [ethereum/pm#846]
## Meeting Info

* [August 9, 2023, 13:00 UTC](https://savvytime.com/converter/utc-to-germany-berlin-united-kingdom-london-ny-new-york-city-ca-san-francisco-china-shanghai-japan-tokyo-australia-sydney/aug-9-2023/13-00)
* Duration: 60 minutes
* Recording: TBA
* Zoom: [ethereumfoundation.zoom.us/j/85035470076?pwd=RFhTTnp6U29UVXpxbW1ZOXp6YTZmUT09](https://ethereumfoundation.zoom.us/j/85035470076?pwd=RFhTTnp6U29UVXpxbW1ZOXp6YTZmUT09)

📆 Subscribe to the [Ethereum Protocol Call calendar](https://calendar.google.com/calendar/u/1?cid=Y191cGFvZm9uZzhtZ3JtcmtlZ243aWM3aGs1c0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t) for calendar invites

## Agenda

* discv5 support in nethermind, interop test planning
* adding available block range into eth protocol handshake

**Comment by holgerd77** [comment]
Is the date of this correct (otherwise issue opened after meeting date if I see correctly)?

**Comment by smartprogrammer93** [comment]
@holgerd77, that is correct. There was no issue, so i thought to add it. So we can track progress.

**Comment by holgerd77** [comment]
> @holgerd77, that is correct. There was no issue, so i thought to add it. So we can track progress.

Ah, ok, thanks!

Short question if you have time to answer, what was the outcome from the call on this: "adding available block range into eth protocol handshake"?

Will this be added and in what form?

I was a bit afraid when reading this that this might lead to the habit of clients to just drop peers with not-useful (so: in a unidirectional sense) block ranges? And this might therefore have some potential to derail the peering experience for clients just starting to sync? 🤔 Or will there be something added like "clients must not drop the peer connection depending on the available block range of the other peer" or similar?

**Comment by smartprogrammer93** [comment]
@holgerd77 honestly I am still drafting the EIP. But this is a valid concern. i think the draft will be discussed next call. Please chime in.

**Comment by smartprogrammer93** [comment]
@fjl @lightclient
I think we can discuss this draft as part of next breakout meeting agenda:
https://hackmd.io/@smartprogrammer/rkqC8y42n
cc, @holgerd77

**Comment by fjl** [comment]
Draft looks pretty good!

**Comment by smartprogrammer93** [comment]
Closed in favor of #858
