### ISSUE TITLE
Consensus-layer Call 122 Agenda

### ISSUE THREAD

**Issue by djrtwo** [ethereum/pm#900]
# Consensus-layer Call 122 Agenda
[prev: call 121](https://github.com/ethereum/pm/issues/898)

Meeting Date/Time: [Thursday 2023/11/16 at 14:00 UTC](https://savvytime.com/converter/utc-to-germany-berlin-united-kingdom-london-ny-new-york-city-ca-san-francisco-china-shanghai-japan-tokyo-australia-sydney/nov-16-2023/2pm)
Meeting Duration: 1.5 hours

[youtube stream](https://youtube.com/live/wSE8e9MZz3k?feature=share)

1. Deneb
    * BlobSidecar networking updates/status
    * serving byRoot requests right after gossip validation https://github.com/ethereum/consensus-specs/issues/3547
3. Research, spec, etc
5. Open Discussion/Closing Remarks

**Comment by tbenr** [comment]
I'd like to have some thoughts on https://github.com/ethereum/consensus-specs/issues/3547
