### ISSUE TITLE
Claim KZG POAP with Github

### ISSUE THREAD

**Issue by CryptoGemzHunter** [ethereum/pm#934]
Hello. I joined KZG Ceremony with my Github acc, not by my EVM Add. I found my github in the script but i can't mint the POAP. Is there any solution for me ?

**Comment by dapplion** [comment]
I would recommend asking in the #kzg-ceremony channel in the Eth R&D discord. Linking invite here, with broken link to for bots :) https://discord.  gg/byPj2wug
