### ISSUE TITLE
Inclusion List Breakout Room

### ISSUE THREAD

**Issue by timbeiko** [ethereum/pm#954]
### Meeting Info
* [Feb 16, 2024, 14:00-15:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20240216T140000&p1=1440&p2=37&p3=136&p4=237&p5=923&p6=204&p7=671&p8=16&p9=41&p10=107&p11=28)
* Recording: https://youtu.be/LhZSunC8Epw
* [Ethereum Protocol Calls Calendar subscription](https://calendar.google.com/calendar/u/0?cid=Y191cGFvZm9uZzhtZ3JtcmtlZ243aWM3aGs1c0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t)

### Agenda
* Inclusion List design discussion tradeoffs 
    * please add links/pre-reads in the comments!

**Comment by michaelneuder** [comment]
heyo! a few recent and relevant docs =)

***Related work***
| **title** | **description** | 
| ---------- | ----------- |
| [proposal](https://ethresear.ch/t/no-free-lunch-a-new-inclusion-list-design/16389) | no free lunch design |
| [censorship.pics](https://censorship.pics/) | toni's dashboard | 
| [unconditional ils](https://ethresear.ch/t/unconditional-inclusion-lists/18500) | unconditional design space |
|[spec overview](https://notes.ethereum.org/@mikeneuder/il-spec-overview)| summary of CL, EELS, and engine api changes |


full list here: https://gist.github.com/michaelneuder/ba32e608c75d48719a7ecba29ec3d64b

**Comment by michaelneuder** [comment]
## rough agenda:
- links: https://gist.github.com/michaelneuder/ba32e608c75d48719a7ecba29ec3d64b
- unconditional: https://ethresear.ch/t/unconditional-inclusion-lists/18500
- spec overview: https://notes.ethereum.org/@mikeneuder/il-spec-overview

.

- short presentation:
  - execution spec: “block validity depends on IL satisfaction”
  - consensus spec: “block not accepted into view without valid list of txns for the IL”
  - engine api: “construct the inclusion list once at the beginning of your slot”
  - design considerations:
    - unconditional
      - extend block or only on when gas is available
      - how to choose size in block extension case
    - ToB vs anywhere in block
    - Summary included in slot n block or slot n+1 block
    - Gossip the txns along with the block or separately
- questions/interactive session
