### ISSUE TITLE
Future EOA/AA Breakout Room 

### ISSUE THREAD

**Issue by timbeiko** [ethereum/pm#962]
### Meeting Info
* [Feb 28, 2024, 14:00-15:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20240228T140000&p1=1440&p2=37&p3=136&p4=237&p5=923&p6=204&p7=671&p8=16&p9=41&p10=107&p11=28)
* Youtube stream: https://youtube.com/live/FfEZdTFAz4E
* Zoom: see the `#future-eoas` channel of the R&D discord 
* [Ethereum Protocol Calls Calendar subscription](https://calendar.google.com/calendar/u/0?cid=Y191cGFvZm9uZzhtZ3JtcmtlZ243aWM3aGs1c0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t)

### Agenda
* (L1) AA desiderata / roadmap 
* Prague AA/EOA-augmentation candidates
    * EIP-3074
    * EIP-5806
    * EIP-7377
    * ERC-4337
    * Other alternatives/proposals
    * Wallet/dev feedback

**Comment by non-fungible-nelson** [comment]
Will we be discussing EIP-7377 or differing to another call?

**Comment by timbeiko** [comment]
Talking with some potential attendees more, I think it may make sense to kick things off with AA desiderata, and then go into specific proposals, @non-fungible-nelson. Happy to include 7377 to the list!

**Comment by GregTheGreek** [comment]
Amazing step forward! Looking forward to the breakout session :)

**Comment by yoavw** [comment]
@timbeiko in case you missed my message in the discord channel last week, I and the rest of the AA team will be on a flight to Denver and won't be able to attend. Would it be possible to change it to one of the other proposed slots? Maybe the one on the 27th?

**Comment by timbeiko** [comment]
@yoavw I asked in the R&D discord and it seems like most other attendees would prefer to keep it Wednesday. Given that, I think the best path forward is to keep the time as-is here, but also recap it on ACDE Thursday and allow for people who couldn't make the breakout to chime in. I've added this to [the agenda](https://github.com/ethereum/pm/issues/961).

**Comment by abcoathup** [comment]
Future of EOA breakout call.  Notes by @TimBeiko (screenshot from Eth R&D Discord)

![image](https://github.com/ethereum/pm/assets/28278242/f505d2a3-4013-422e-98a1-4d543ee8b66a)


Recording: https://www.youtube.com/watch?v=FfEZdTFAz4E&t=46s

Full text:
Very quick recap of the ⁠future-eoa [Discord channel] breakout leading into tomorrow's call [ACDE]:
* There are many open questions around the long-term AA roadmap, how L1 vs. L2 support for larger changes would look like, and what should be enshrined vs. not.
* There are a handful of smaller proposals that we could do in Pectra, but we want to make sure we don't do something that prevents us from adopting AAs more broadly in the future.
* We didn't cover 4337 much given the core team couldn't make it to the breakout, but hopefully they can come on tomorrow to give an overview of their roadmap.

Not sure we'll be able to get consensus on if and what to ship in Prague, but hopefully we can cover the 4337 roadmap, L1 vs. L2 concerns (mostly client support for L2-specific features), and the differences between the various short term proposals.

**Comment by abcoathup** [comment]
Notes by Dom: https://notes.ethereum.org/QT9e9r6NRdSOjWRBzA3JLA
