### ISSUE TITLE
RollCall #3.1 Breakout: Shared Sequencing & Pre-Confirmations

### ISSUE THREAD

**Issue by adietrichs** [ethereum/pm#970]
As announced on [RollCall #3](https://github.com/ethereum/pm/issues/944), @JustinDrake has offered to lead a breakout call this week on shared sequencing and pre-confirmations. The intention is for these breakout calls to be optional additions to the monthly RollCalls, and aimed at bringing together the subset of teams interested in each particular topic.

## Meeting Info

* [Wed Feb 28, 2024, 15:00-16:30 UTC](https://savvytime.com/converter/utc-to-germany-berlin-united-kingdom-london-ny-new-york-city-ca-san-francisco-china-shanghai-japan-tokyo-australia-sydney/feb-28-2024/3pm) **NOTE: 1H LATER THAN USUAL**
* * Zoom link shared in the `rollcall` channel in the [EthR&D Discord](https://discord.com/invite/qGpsxSA), which is bridged to the RollCall telegram channel, shortly before the call.

## Questions

If you have questions in advance that you would like Justin to address, leave them in the comments here!

**Comment by kelemeno** [comment]
Will the topics of this call be similar to the "Shared sequencing and preconfirmations" calls? Or because it is a rollcall, maybe it will be more rollup focused?
